(function(){
  'use strict';
  const $=id=>document.getElementById(id),math=window.ACInvoiceMath,api=window.ACInvoiceAPI,pdf=window.ACInvoicePDF;
  const STATUS=['Draft','Issued','Sent','Partially Paid','Paid','Overdue','Cancelled'];
  let invoices=[],settings={...api.DEFAULT_SETTINGS},current=null,currentItems=[],role='',logoData='',busy=false;
  const esc=value=>String(value==null?'':value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const today=()=>{const value=new Date(),offset=value.getTimezoneOffset();return new Date(value.getTime()-offset*60000).toISOString().slice(0,10)};
  const addDays=(value,days)=>{const date=new Date(`${value}T00:00:00`);date.setDate(date.getDate()+days);return date.toISOString().slice(0,10)};
  const number=value=>{const parsed=Number(value);return Number.isFinite(parsed)?parsed:0};
  const clone=value=>JSON.parse(JSON.stringify(value));
  function notify(message,error=false){const toast=$('toast');toast.textContent=message;toast.style.background=error?'#ef6b64':'#f5b400';toast.classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>toast.classList.remove('show'),3000)}
  function friendly(error){const text=error?.message||String(error||'Unexpected error');if(/ac_invoices|schema cache|relation.+does not exist/i.test(text))return'The Invoice database migration has not been installed in Supabase yet.';return text}
  function setBusy(value,label='Working…'){busy=value;document.querySelectorAll('button').forEach(button=>{if(button.closest('.ac-platform'))return;button.disabled=value});if(value)notify(label)}
  function defaultItem(){return{title:'',description:'',quantity:1,unit:'each',base_cost:0,profit_type:'',profit_value:'',gst_applicable:true}}
  function emptyInvoice(){return{id:'',invoice_number:'',issue_date:today(),due_date:addDays(today(),14),status:'Draft',project_id:'',project_name:'',project_address:'',customer_id:'',customer_name:'',customer_company:'',customer_address:'',customer_email:'',customer_phone:'',customer_abn:'',quote_id:'',reference_no:'',notes:'',private_notes:'',payment_terms:settings.payment_terms||'',default_profit_type:settings.default_profit_type||'percent',default_profit_value:number(settings.default_profit_value||20),gst_enabled:true,gst_rate:number(settings.gst_rate||10),discount_amount:0,amount_paid:0,pdf_path:'',pdf_filename:''}}
  function itemsOf(invoice){return[...(invoice?.ac_invoice_items||invoice?.items||[])].map(item=>({...item,...(Array.isArray(item.ac_invoice_item_costs)?item.ac_invoice_item_costs[0]||{}:item.ac_invoice_item_costs||{})})).sort((a,b)=>number(a.position)-number(b.position))}
  function statusClass(value){return String(value||'').toLowerCase().replace(/\s+/g,'-')}
  function effectiveStatus(invoice){const value=invoice.status||'Draft';if(!['Draft','Paid','Cancelled','Overdue'].includes(value)&&number(invoice.balance_due)>0&&invoice.due_date&&invoice.due_date<today())return'Overdue';return value}
  function dateText(value){if(!value)return'-';const parsed=new Date(`${value}T00:00:00`);return Number.isNaN(parsed.getTime())?value:parsed.toLocaleDateString('en-AU',{day:'numeric',month:'short',year:'numeric'})}

  function applyRole(){
    const manager=role==='manager',owner=role==='owner';
    document.querySelectorAll('.edit-only').forEach(element=>element.hidden=manager);
    document.querySelectorAll('.owner-only').forEach(element=>element.hidden=!owner);
    $('invoiceForm').querySelectorAll('input,select,textarea,button').forEach(control=>control.disabled=manager);
    $('roleNotice').innerHTML=manager?'<strong>Manager · Read Only</strong> You can view, filter, preview, print and download PDFs already created. All editing, status, payment and PDF-generation actions are blocked by both the interface and Supabase.':owner?'<strong>Owner · Full Access</strong> Create, edit, delete, issue, record payments, generate PDFs and manage company invoice settings.':'<strong>Estimator · Create & Edit</strong> Create, edit, duplicate, print and generate invoices. Payment status, amount paid and company settings remain Owner-only.';
  }
  function projectOptions(){
    const local=window.ACProjects?.list?.()||[],byId=new Map(local.map(project=>[project.id,project]));
    invoices.forEach(invoice=>{if(invoice.project_id&&!byId.has(invoice.project_id))byId.set(invoice.project_id,{id:invoice.project_id,name:invoice.project_name||'Linked project',address:invoice.project_address||'',client:invoice.customer_name||''})});
    const options=[...byId.values()].map(project=>`<option value="${esc(project.id)}">${esc(project.name)}</option>`).join('');
    $('filterProject').innerHTML='<option value="">All projects</option>'+options;$('projectId').innerHTML='<option value="">No linked project</option>'+options;
  }
  function quoteOptions(projectId,selected=''){
    const project=window.ACProjects?.get?.(projectId),records=(project?.records||[]).filter(record=>['quote-analysis','electrical','plumbing','cladding','plan-estimate','renovation-budget'].includes(record.module));
    let options=records.map(record=>`<option value="${esc(record.id)}">${esc(record.title||record.summary||'Saved project record')}</option>`).join('');
    if(selected&&!records.some(record=>record.id===selected))options=`<option value="${esc(selected)}">Linked record ${esc(selected.slice(0,8))}</option>`+options;
    $('quoteId').innerHTML='<option value="">No linked quote</option>'+options;$('quoteId').value=selected||'';
  }
  function renderList(){
    const query=$('filterSearch').value.trim().toLowerCase(),status=$('filterStatus').value,project=$('filterProject').value,from=$('filterFrom').value,to=$('filterTo').value;
    const rows=invoices.filter(invoice=>{
      const haystack=[invoice.invoice_number,invoice.customer_name,invoice.customer_company,invoice.project_name,invoice.reference_no].join(' ').toLowerCase(),actual=effectiveStatus(invoice);
      return(!query||haystack.includes(query))&&(!status||actual===status)&&(!project||invoice.project_id===project)&&(!from||invoice.issue_date>=from)&&(!to||invoice.issue_date<=to);
    });
    $('invoiceRows').innerHTML=rows.map(invoice=>{const statusValue=effectiveStatus(invoice);return`<tr data-id="${esc(invoice.id)}"><td><strong>${esc(invoice.invoice_number)}</strong><span>${esc(invoice.reference_no||'No reference')}</span></td><td><strong>${esc(invoice.customer_name||invoice.customer_company||'Unnamed customer')}</strong><span>${esc(invoice.project_name||'No linked project')}</span></td><td>${esc(dateText(invoice.issue_date))}</td><td><span class="status ${statusClass(statusValue)}">${esc(statusValue)}</span></td><td class="amount">${esc(math.formatAUD(invoice.total_amount))}</td><td class="amount">${esc(math.formatAUD(invoice.balance_due))}</td><td><button class="open-invoice secondary" type="button">Open</button></td></tr>`}).join('');
    $('listState').hidden=rows.length>0;$('listState').textContent=invoices.length?(rows.length?'':'No invoices match these filters.'):'No invoices yet. Create the first professional tax invoice.';
    $('invoiceRows').querySelectorAll('tr').forEach(row=>row.querySelector('.open-invoice').addEventListener('click',()=>openEditor(invoices.find(invoice=>invoice.id===row.dataset.id))));
  }
  async function loadAll(){
    $('listState').hidden=false;$('listState').textContent='Loading invoices…';
    try{const result=await Promise.all([api.list(),api.settings()]);invoices=Array.isArray(result[0])?result[0]:[];settings=result[1];logoData=await api.logoDataUrl(settings.logo_path).catch(()=>new URL('../assets/invoice-logo.png',location.href).href);projectOptions();renderList();fillSettings()}
    catch(error){$('listState').hidden=false;$('listState').textContent=friendly(error);notify(friendly(error),true)}
  }
  function showView(name){$('listView').classList.toggle('show',name==='list');$('editorView').classList.toggle('show',name==='editor');if(name==='list'){$('previewSection').hidden=true;scrollTo({top:0,behavior:'smooth'})}}
  function setValue(id,value){const element=$(id);if(element)element.value=value==null?'':value}
  function populate(invoice){
    const map={invoiceNumber:'invoice_number',issueDate:'issue_date',dueDate:'due_date',invoiceStatus:'status',projectId:'project_id',projectName:'project_name',projectAddress:'project_address',referenceNo:'reference_no',customerName:'customer_name',customerCompany:'customer_company',customerAddress:'customer_address',customerEmail:'customer_email',customerPhone:'customer_phone',customerAbn:'customer_abn',defaultProfitType:'default_profit_type',defaultProfitValue:'default_profit_value',gstRate:'gst_rate',discountAmount:'discount_amount',amountPaid:'amount_paid',paymentTerms:'payment_terms',notes:'notes',privateNotes:'private_notes'};
    Object.entries(map).forEach(([id,key])=>setValue(id,invoice[key]));quoteOptions(invoice.project_id,invoice.quote_id);$('gstEnabled').checked=invoice.gst_enabled!==false;
    $('editorKicker').textContent=`${invoice.status||'Draft'} INVOICE`;$('editorTitle').textContent=invoice.invoice_number||'New invoice';$('downloadSavedBtn').hidden=!invoice.pdf_path;$('deleteBtn').hidden=role!=='owner'||!invoice.id;
  }
  function openEditor(invoice,duplicate=false){
    current=invoice?clone(invoice):emptyInvoice();
    if(duplicate){current={...current,id:'',invoice_number:'',status:'Draft',amount_paid:0,pdf_path:'',pdf_filename:'',created_at:null,updated_at:null};current.issue_date=today();current.due_date=addDays(today(),14)}
    currentItems=invoice?itemsOf(invoice).map(item=>({...item,id:duplicate?'':item.id})): [defaultItem()];
    if(!currentItems.length)currentItems=[defaultItem()];populate(current);renderItems();applyRole();updateLive();showView('editor');
  }
  function readInvoice(){return{
    ...current,invoice_number:$('invoiceNumber').value,issue_date:$('issueDate').value,due_date:$('dueDate').value,status:$('invoiceStatus').value||current.status||'Draft',project_id:$('projectId').value,quote_id:$('quoteId').value,project_name:$('projectName').value.trim(),project_address:$('projectAddress').value.trim(),reference_no:$('referenceNo').value.trim(),customer_name:$('customerName').value.trim(),customer_company:$('customerCompany').value.trim(),customer_address:$('customerAddress').value.trim(),customer_email:$('customerEmail').value.trim(),customer_phone:$('customerPhone').value.trim(),customer_abn:$('customerAbn').value.trim(),default_profit_type:$('defaultProfitType').value,default_profit_value:number($('defaultProfitValue').value),gst_enabled:$('gstEnabled').checked,gst_rate:number($('gstRate').value),discount_amount:number($('discountAmount').value),amount_paid:number($('amountPaid').value),payment_terms:$('paymentTerms').value.trim(),notes:$('notes').value.trim(),private_notes:$('privateNotes').value.trim()
  }}
  function syncItems(){currentItems=[...$('items').querySelectorAll('.item-row')].map((row,index)=>({
    ...(currentItems[index]||{}),id:row.dataset.id||'',title:row.querySelector('[data-field="title"]').value.trim(),description:row.querySelector('[data-field="description"]').value.trim(),quantity:number(row.querySelector('[data-field="quantity"]').value),unit:row.querySelector('[data-field="unit"]').value.trim(),base_cost:number(row.querySelector('[data-field="base_cost"]').value),profit_type:row.querySelector('[data-field="profit_type"]').value,profit_value:row.querySelector('[data-field="profit_value"]').value===''?'':number(row.querySelector('[data-field="profit_value"]').value),gst_applicable:row.querySelector('[data-field="gst_applicable"]').checked
  }))}
  function currentTotals(invoice=readInvoice()){return role==='manager'?{items:currentItems,subtotal:number(current.subtotal),discount_amount:number(current.discount_amount),profit_amount:0,gst_amount:number(current.gst_amount),total_amount:number(current.total_amount),amount_paid:number(current.amount_paid),balance_due:number(current.balance_due),gst_rate:number(current.gst_rate)}:math.calculateInvoice(invoice,currentItems)}
  function renderItems(){
    $('items').innerHTML=currentItems.map((item,index)=>`<div class="item-row" data-index="${index}" data-id="${esc(item.id||'')}"><label><span>Item / service</span><input data-field="title" value="${esc(item.title)}" placeholder="e.g. Demolition"></label><label><span>Description</span><textarea data-field="description" placeholder="Scope included">${esc(item.description)}</textarea></label><label><span>Qty</span><input data-field="quantity" type="number" min="0" step="0.01" value="${esc(item.quantity)}"></label><label><span>Unit</span><input data-field="unit" value="${esc(item.unit||'each')}"></label><label class="edit-only"><span>Base cost</span><input data-field="base_cost" type="number" min="0" step="0.01" value="${esc(item.base_cost)}"></label><label class="edit-only"><span>Profit type</span><select data-field="profit_type"><option value="" ${!item.profit_type?'selected':''}>Default</option><option value="percent" ${item.profit_type==='percent'?'selected':''}>%</option><option value="fixed" ${item.profit_type==='fixed'?'selected':''}>Fixed</option></select></label><label class="edit-only"><span>Profit value</span><input data-field="profit_value" type="number" min="0" step="0.01" value="${item.profit_value==null?'':esc(item.profit_value)}" placeholder="Default"></label><label class="item-gst"><input data-field="gst_applicable" type="checkbox" ${item.gst_applicable!==false?'checked':''}> GST</label><div class="line-total" data-line-total>$0.00</div><button class="remove-item edit-only" type="button" aria-label="Remove item">×</button></div>`).join('');
    $('items').querySelectorAll('input,select,textarea').forEach(control=>control.addEventListener('input',updateLive));$('items').querySelectorAll('.remove-item').forEach((button,index)=>button.addEventListener('click',()=>{syncItems();currentItems.splice(index,1);if(!currentItems.length)currentItems.push(defaultItem());renderItems();applyRole();updateLive()}));applyRole();
  }
  function updateLive(){
    if(!current)return;syncItems();const invoice=readInvoice(),totals=currentTotals(invoice);
    $('summarySubtotal').textContent=math.formatAUD(totals.subtotal);$('summaryDiscount').textContent=math.formatAUD(-totals.discount_amount);$('discountRow').hidden=!totals.discount_amount;$('gstLabel').textContent=`GST ${number(totals.gst_rate).toFixed(0)}%`;$('summaryGst').textContent=math.formatAUD(totals.gst_amount);$('summaryTotal').textContent=math.formatAUD(totals.total_amount);$('summaryPaid').textContent=math.formatAUD(totals.amount_paid);$('summaryBalance').textContent=math.formatAUD(totals.balance_due);$('summaryProfit').textContent=math.formatAUD(totals.profit_amount);
    $('items').querySelectorAll('[data-line-total]').forEach((element,index)=>element.textContent=math.formatAUD(totals.items[index]?.line_subtotal||0));if(!$('previewSection').hidden)renderPreview(invoice,totals);
  }
  function validate(invoice,items){if(!invoice.issue_date||!invoice.due_date)throw new Error('Enter the issue and due dates.');if(!invoice.customer_name&&!invoice.customer_company)throw new Error('Enter a customer name or company.');if(!items.length||items.some(item=>!item.title))throw new Error('Every invoice item needs a title.');if(items.some(item=>item.quantity<0||item.base_cost<0))throw new Error('Item quantities and costs cannot be negative.');if(invoice.due_date<invoice.issue_date)throw new Error('The due date cannot be before the issue date.')}
  async function saveCurrent(){
    if(role==='manager')throw new Error('Manager access is read only.');syncItems();const invoice=readInvoice();validate(invoice,currentItems);setBusy(true,current?.id?'Saving invoice…':'Creating draft…');
    try{const saved=current?.id?await api.update(current.id,invoice,currentItems):await api.create(invoice,currentItems);current=Array.isArray(saved)?saved[0]:saved;currentItems=itemsOf(current);populate(current);renderItems();await loadAll();notify(current.invoice_number+' saved');return current}
    finally{setBusy(false)}
  }
  function renderPreview(invoice=readInvoice(),totals=currentTotals(invoice)){
    const lines=totals.items.map(item=>`<tr><td><strong>${esc(item.title)}</strong></td><td>${esc(item.description).replace(/\n/g,'<br>')}${item.gst_applicable===false?'<small>GST-free item</small>':''}</td><td>${esc(item.quantity)}</td><td>${esc(item.unit)}</td><td>${esc(math.formatAUD(item.selling_unit_price))}</td><td>${esc(math.formatAUD(item.line_subtotal))}</td></tr>`).join('');
    const company=[settings.address,settings.phone,settings.email,settings.website,settings.abn?`ABN ${settings.abn}`:''].filter(Boolean).map(value=>`<p>${esc(value).replace(/\n/g,'<br>')}</p>`).join(''),customer=[invoice.customer_company&&invoice.customer_company!==invoice.customer_name?invoice.customer_company:'',invoice.customer_address,invoice.customer_email,invoice.customer_phone,invoice.customer_abn?`ABN ${invoice.customer_abn}`:''].filter(Boolean).map(value=>`<p>${esc(value).replace(/\n/g,'<br>')}</p>`).join('');
    $('invoicePreview').innerHTML=`<header class="preview-company"><div><h2>${esc(settings.company_name)}</h2>${company}</div><img class="preview-logo" src="${esc(logoData||'../assets/invoice-logo.png')}" alt="Company logo"></header><div class="preview-title">TAX INVOICE</div><section class="preview-parties"><div><span class="label">INVOICE TO</span><h3>${esc(invoice.customer_name||invoice.customer_company||'-')}</h3>${customer}</div><div class="preview-meta"><div><span>INVOICE</span><strong>${esc(invoice.invoice_number||'DRAFT')}</strong></div><div><span>DATE</span><strong>${esc(dateText(invoice.issue_date))}</strong></div><div><span>DUE DATE</span><strong>${esc(dateText(invoice.due_date))}</strong></div><div><span>PROJECT</span><strong>${esc(invoice.project_name||'-')}</strong></div>${invoice.reference_no?`<div><span>REFERENCE</span><strong>${esc(invoice.reference_no)}</strong></div>`:''}</div></section><table class="preview-items"><thead><tr><th>ITEM</th><th>DESCRIPTION</th><th>QTY</th><th>UNIT</th><th>RATE</th><th>AMOUNT</th></tr></thead><tbody>${lines||'<tr><td colspan="6">No items</td></tr>'}</tbody></table><div class="preview-totals"><div><span>Subtotal excluding GST</span><strong>${esc(math.formatAUD(totals.subtotal))}</strong></div>${totals.discount_amount?`<div><span>Discount</span><strong>${esc(math.formatAUD(-totals.discount_amount))}</strong></div>`:''}<div><span>GST ${esc(number(totals.gst_rate).toFixed(0))}%</span><strong>${esc(math.formatAUD(totals.gst_amount))}</strong></div><div><span>Total including GST</span><strong>${esc(math.formatAUD(totals.total_amount))}</strong></div><div><span>Amount Paid</span><strong>${esc(math.formatAUD(totals.amount_paid))}</strong></div><div class="balance"><span>BALANCE DUE</span><strong>${esc(math.formatAUD(totals.balance_due,true))}</strong></div></div><section class="preview-payment"><h4>PAYMENT DETAILS</h4><p>${esc([settings.bank_account_name,settings.bank_bsb?`BSB: ${settings.bank_bsb}`:'',settings.bank_account_number?`Account: ${settings.bank_account_number}`:''].filter(Boolean).join(' · '))}</p><h4>PAYMENT TERMS</h4><p>${esc(invoice.payment_terms||settings.payment_terms).replace(/\n/g,'<br>')}</p>${invoice.notes?`<h4>NOTES</h4><p>${esc(invoice.notes).replace(/\n/g,'<br>')}</p>`:''}</section><footer class="preview-footer">${esc(settings.company_name)} · ${esc(settings.email)} · Amounts in AUD</footer>`;
  }
  async function generate(){
    if(role==='manager')return notify('Manager access cannot generate a new PDF.',true);
    try{if(!current?.id)await saveCurrent();else{syncItems();validate(readInvoice(),currentItems);await saveCurrent()}const invoice=readInvoice(),totals=math.calculateInvoice(invoice,currentItems),result=pdf.buildInvoicePdf(invoice,currentItems,settings,{totals,logoData});api.downloadBlob(result.blob,result.filename);notify('PDF downloaded. Saving a secure copy…');try{const path=await api.uploadPdf(current,result.blob,result.filename),saved=await api.recordPdf(current.id,path,result.filename,result.blob.size);current=Array.isArray(saved)?saved[0]:saved;$('downloadSavedBtn').hidden=false;await loadAll();notify('PDF downloaded and saved securely')}catch(error){notify('PDF downloaded, but the secure copy was not saved: '+friendly(error),true)}}catch(error){notify(friendly(error),true)}
  }
  async function downloadSaved(){try{const blob=await api.pdfBlob(current.pdf_path);api.downloadBlob(blob,current.pdf_filename||pdf.filename(current))}catch(error){notify(friendly(error),true)}}
  function fillSettings(){const values={companyName:'company_name',companyAbn:'abn',companyAddress:'address',companyPhone:'phone',companyEmail:'email',companyWebsite:'website',bankAccountName:'bank_account_name',bankBsb:'bank_bsb',bankAccountNumber:'bank_account_number',defaultPaymentTerms:'payment_terms',settingsProfitType:'default_profit_type',settingsProfitValue:'default_profit_value',settingsGstRate:'gst_rate'};Object.entries(values).forEach(([id,key])=>setValue(id,settings[key]));$('settingsLogo').src=logoData||'../assets/invoice-logo.png'}
  function openSettings(){fillSettings();$('settingsModal').classList.add('show');$('settingsModal').setAttribute('aria-hidden','false')}
  function closeSettings(){$('settingsModal').classList.remove('show');$('settingsModal').setAttribute('aria-hidden','true');$('logoFile').value=''}
  async function saveCompanySettings(event){
    event.preventDefault();if(role!=='owner')return notify('Only the Owner can change company settings.',true);setBusy(true,'Saving company settings…');
    try{let logoPath=settings.logo_path||'',file=$('logoFile').files[0];if(file)logoPath=await api.uploadLogo(file);const next={company_name:$('companyName').value.trim(),abn:$('companyAbn').value.trim(),address:$('companyAddress').value.trim(),phone:$('companyPhone').value.trim(),email:$('companyEmail').value.trim(),website:$('companyWebsite').value.trim(),bank_account_name:$('bankAccountName').value.trim(),bank_bsb:$('bankBsb').value.trim(),bank_account_number:$('bankAccountNumber').value.trim(),payment_terms:$('defaultPaymentTerms').value.trim(),default_profit_type:$('settingsProfitType').value,default_profit_value:number($('settingsProfitValue').value),gst_rate:number($('settingsGstRate').value),logo_path:logoPath};settings={...settings,...(await api.saveSettings(next))};logoData=await api.logoDataUrl(settings.logo_path);closeSettings();notify('Company invoice settings saved')}catch(error){notify(friendly(error),true)}finally{setBusy(false)}
  }

  function bind(){
    $('newInvoiceBtn').addEventListener('click',()=>openEditor());$('backBtn').addEventListener('click',()=>showView('list'));$('saveBtn').addEventListener('click',()=>saveCurrent().catch(error=>notify(friendly(error),true)));$('previewBtn').addEventListener('click',()=>{$('previewSection').hidden=false;renderPreview();$('previewSection').scrollIntoView({behavior:'smooth'})});$('closePreviewBtn').addEventListener('click',()=>{$('previewSection').hidden=true});$('generateBtn').addEventListener('click',generate);$('downloadSavedBtn').addEventListener('click',downloadSaved);$('duplicateBtn').addEventListener('click',()=>{syncItems();openEditor({...readInvoice(),ac_invoice_items:clone(currentItems)},true)});$('printBtn').addEventListener('click',()=>{$('previewSection').hidden=false;renderPreview();setTimeout(()=>window.print(),60)});$('deleteBtn').addEventListener('click',async()=>{if(role!=='owner'||!current?.id||!confirm(`Delete ${current.invoice_number}? This cannot be undone.`))return;try{await api.remove(current.id);notify('Invoice deleted');await loadAll();showView('list')}catch(error){notify(friendly(error),true)}});
    $('addItemBtn').addEventListener('click',()=>{syncItems();currentItems.push(defaultItem());renderItems();updateLive()});$('invoiceForm').addEventListener('input',updateLive);$('projectId').addEventListener('change',()=>{const project=window.ACProjects?.get?.($('projectId').value);quoteOptions($('projectId').value);if(project){$('projectName').value=project.name||'';$('projectAddress').value=project.address||'';if(!$('customerName').value)$('customerName').value=project.client||''}updateLive()});
    ['filterSearch','filterStatus','filterProject','filterFrom','filterTo'].forEach(id=>$(id).addEventListener('input',renderList));$('clearFilters').addEventListener('click',()=>{['filterSearch','filterStatus','filterProject','filterFrom','filterTo'].forEach(id=>$(id).value='');renderList()});
    $('settingsBtn').addEventListener('click',openSettings);$('closeSettingsBtn').addEventListener('click',closeSettings);$('cancelSettingsBtn').addEventListener('click',closeSettings);$('settingsModal').addEventListener('click',event=>{if(event.target===$('settingsModal'))closeSettings()});$('settingsForm').addEventListener('submit',saveCompanySettings);$('logoFile').addEventListener('change',()=>{const file=$('logoFile').files[0];if(file)$('settingsLogo').src=URL.createObjectURL(file)});
  }
  async function init(){
    await window.ACAuth.ready;role=window.ACAuth.role();if(!api.ACCESS_ROLES.has(role))return;bind();applyRole();await loadAll();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
