(function () {
  'use strict';
  const $ = id => document.getElementById(id); let data = null;
  const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
  const nice = value => String(value || '—').replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
  const date = value => value ? new Date(value).toLocaleDateString('en-AU', { day: 'numeric', month: 'short', year: 'numeric' }) : '—';
  const money = value => new Intl.NumberFormat('en-AU', { style: 'currency', currency: 'AUD' }).format(Number(value || 0));
  function safeName() { if (ACWorkflow.preview) return 'John Smith'; const customer = ACAuth.customerProfile() || {}, user = ACAuth.user() || {}; return customer.full_name || String(user.email || 'Customer').split('@')[0]; }
  function safeEmail() { if (ACWorkflow.preview) return 'john.smith@example.com'; const customer = ACAuth.customerProfile() || {}, user = ACAuth.user() || {}; return user.email || customer.email || 'Verified customer'; }
  function view(name) { document.querySelectorAll('[data-panel]').forEach(node => node.classList.toggle('active', node.dataset.panel === name)); document.querySelectorAll('[data-view]').forEach(node => node.classList.toggle('active', node.dataset.view === name)); const labels = { dashboard: ['Customer overview', `Good afternoon, <b>${escapeHtml(safeName())}</b>.`], requests: ['Your enquiries', 'My Requests'], projects: ['Approved work', 'My Projects'], appointments: ['Visits & meetings', 'Appointments'], messages: ['Customer communication', 'Messages'], documents: ['Shared files', 'Documents'], quotes: ['Commercial documents', 'Quotes & Invoices'], account: ['Secure account', 'Account'] }; $('viewKicker').textContent = labels[name]?.[0] || 'Customer Portal'; $('viewTitle').innerHTML = labels[name]?.[1] || 'Customer Portal'; document.getElementById('portal').classList.remove('side-open'); }
  function projectCard(project) { return `<article class="cp-list-card"><div><h3>${escapeHtml(project.name)}</h3><p>${escapeHtml(project.address || '')}</p><div class="cp-list-card-meta"><span>${escapeHtml(project.project_number || '')}</span><span>${nice(project.customer_status || project.status)}</span><span>Updated ${date(project.updated_at)}</span></div></div><div class="cp-list-card-actions"><span class="cp-status">${nice(project.customer_status || project.status)}</span><button class="cp-btn" data-open-project="${project.id}">View timeline</button></div></article>`; }
  function requestCard(request) { return `<article class="cp-list-card"><div><h3>${escapeHtml(request.request_number)} · ${escapeHtml((request.services || []).join(', '))}</h3><p>${escapeHtml(request.address)}, ${escapeHtml(request.suburb)} · submitted ${date(request.created_at)}</p><div class="cp-list-card-meta"><span>${nice(request.status)}</span><span>${escapeHtml(request.preferred_contact || '')} contact</span></div></div><span class="cp-status">${nice(request.status)}</span></article>`; }
  function renderProjectDetail(project) { const stages = ['Request Submitted', 'Under Admin Review', 'Site Visit Scheduled', 'Site Inspection Completed', 'Estimate in Preparation', 'Quote Sent', 'Quote Accepted', 'Project Scheduled', 'Work in Progress', 'Project Completed']; const current = stages.findIndex(stage => stage.toLowerCase() === String(project.customer_status || '').toLowerCase()); const index = current >= 0 ? current : Math.round((project.progress || 0) / 10); $('projectDetail').hidden = false; $('projectDetail').innerHTML = `<h3>${escapeHtml(project.name)}</h3><p>${escapeHtml(project.address || '')}</p><div class="cp-timeline">${stages.map((stage, i) => `<article class="${i <= index ? 'done' : ''}"><strong>${stage}</strong><span>${i <= index ? 'Completed or active' : 'Upcoming'}</span></article>`).join('')}</div>`; $('projectDetail').scrollIntoView({ behavior: 'smooth', block: 'start' }); }
  function render() {
    const requests = data.requests || [], projects = data.projects || [], appointments = data.appointments || [], quotes = data.quotes || [], notes = data.notes || [], messages = data.messages || [], documents = data.documents || [];
    $('requestBadge').textContent = requests.length; $('projectBadge').textContent = projects.length; $('activeRequestCount').textContent = requests.filter(item => !['not_suitable', 'closed'].includes(item.status)).length; $('currentProjectCount').textContent = projects.filter(item => item.status !== 'completed').length; $('appointmentCount').textContent = appointments.length; $('quoteCount').textContent = quotes.filter(item => ['sent', 'viewed'].includes(item.status)).length;
    $('requestList').innerHTML = requests.length ? requests.map(requestCard).join('') : '<div class="cp-empty"><b>＋</b><h3>No requests yet</h3><p>Submit your first job request when you are ready.</p></div>';
    $('projectList').innerHTML = projects.length ? projects.map(projectCard).join('') : '<div class="cp-empty"><b>▱</b><h3>No approved projects yet</h3><p>A project appears after the Admin team approves a request and assigns the next stage.</p></div>';
    $('appointmentList').innerHTML = appointments.length ? appointments.map(item => `<article class="cp-list-card"><div><h3>${escapeHtml(item.title)}</h3><p>${new Date(item.starts_at).toLocaleString('en-AU', { dateStyle: 'full', timeStyle: 'short' })}</p></div><span class="cp-status">${nice(item.status)}</span></article>`).join('') : '<div class="cp-empty"><b>◷</b><h3>No appointments scheduled</h3><p>Confirmed site visits and meetings appear here.</p></div>';
    $('quoteList').innerHTML = quotes.length ? quotes.map(item => `<article class="cp-list-card"><div><h3>${escapeHtml(item.quote_number)} · ${escapeHtml(item.title)}</h3><p>Valid until ${date(item.valid_until)} · GST included</p></div><div class="cp-list-card-actions"><strong>${money(item.total)}</strong><span class="cp-status">${nice(item.status)}</span>${['sent','viewed'].includes(item.status) ? `<div><button class="cp-btn primary" data-quote-decision="accepted" data-quote="${item.id}">Accept quote</button><button class="cp-btn" data-quote-decision="declined" data-quote="${item.id}">Decline</button></div>` : ''}</div></article>`).join('') : '';
    $('invoiceList').innerHTML = (data.invoices || []).length ? data.invoices.map(item => `<article class="cp-list-card"><div><h3>${escapeHtml(item.invoice_number)}</h3><p>Due ${date(item.due_date)}</p></div><div class="cp-list-card-actions"><strong>${money(item.total)}</strong><span class="cp-status">${nice(item.status)}</span></div></article>`).join('') : (!quotes.length ? '<div class="cp-empty"><b>$</b><h3>No quotes or invoices shared</h3><p>Only formally issued customer documents appear here.</p></div>' : '');
    const project = projects[0]; $('latestProject').innerHTML = project ? `<div class="cp-project-preview"><div class="cp-project-preview-top"><div><h3>${escapeHtml(project.name)}</h3><p>${escapeHtml(project.address || '')}</p></div><span class="cp-status">${nice(project.customer_status || project.status)}</span></div><div class="cp-progress"><i style="width:${Number(project.progress || 0)}%"></i></div><div class="cp-project-meta"><div><small>Progress</small><strong>${Number(project.progress || 0)}%</strong></div><div><small>Next step</small><strong>${nice(project.customer_status || project.status)}</strong></div><div><small>Site visit</small><strong>${date(project.site_visit_at)}</strong></div></div></div>` : '<div class="cp-empty"><h3>No current project</h3><p>Approved work will appear here.</p></div>';
    $('customerUpdates').innerHTML = notes.length ? notes.slice(0, 5).map(item => `<article><strong>${escapeHtml(item.body)}</strong><span>${date(item.created_at)}</span></article>`).join('') : '<div class="cp-empty"><p>No project updates yet.</p></div>';
    $('messageList').innerHTML = messages.length ? messages.map(item => `<article><strong>${item.sender_scope === 'customer' ? 'You' : 'Alert Construction'}</strong><p>${escapeHtml(item.body)}</p><span>${new Date(item.created_at).toLocaleString('en-AU', { dateStyle: 'medium', timeStyle: 'short' })}</span></article>`).join('') : '<div class="cp-empty"><b>✦</b><h3>No customer messages yet</h3><p>Send a secure message when you need to ask the project team a question.</p></div>';
    $('messageForm').elements.project_id.innerHTML = projects.map(item => `<option value="${item.id}">${escapeHtml(item.name)}</option>`).join('');
    $('messageForm').querySelector('button').disabled = projects.length === 0;
    $('documentList').innerHTML = documents.length ? documents.map(item => `<article class="cp-list-card"><div><h3>${escapeHtml(item.file_name)}</h3><p>${escapeHtml(item.category || 'Project document')} · ${Math.max(1, Math.round(Number(item.size_bytes || 0) / 1024))} KB · shared ${date(item.created_at)}</p></div><button class="cp-btn" data-download-document="${item.id}">Download</button></article>`).join('') : '<div class="cp-empty"><b>□</b><h3>No shared documents yet</h3><p>Your original request files remain attached securely to the request.</p></div>';
    document.querySelectorAll('[data-open-project]').forEach(button => button.addEventListener('click', () => renderProjectDetail(projects.find(item => item.id === button.dataset.openProject))));
    document.querySelectorAll('[data-quote-decision]').forEach(button => button.addEventListener('click', async () => { const label = button.dataset.quoteDecision === 'accepted' ? 'accept' : 'decline'; if (!confirm(`Are you sure you want to ${label} this quote?`)) return; try { await ACWorkflow.decideQuote(button.dataset.quote, button.dataset.quoteDecision); data = await ACWorkflow.customerSnapshot(); render(); } catch (error) { $('alert').textContent = error.message; $('alert').hidden = false; } }));
    document.querySelectorAll('[data-download-document]').forEach(button => button.addEventListener('click', async () => { const record = documents.find(item => item.id === button.dataset.downloadDocument); if (!record) return; try { const result = await ACWorkflow.downloadProjectDocument(record); if (result.preview) alert(`${record.file_name} is a preview-only sample document.`); } catch (error) { $('alert').textContent = error.message; $('alert').hidden = false; } }));
  }
  document.querySelectorAll('[data-view]').forEach(button => button.addEventListener('click', () => view(button.dataset.view))); document.querySelectorAll('[data-go]').forEach(button => button.addEventListener('click', () => view(button.dataset.go)));
  $('menu').addEventListener('click', () => $('portal').classList.toggle('side-open')); $('backdrop').addEventListener('click', () => $('portal').classList.remove('side-open'));
  $('signOut').addEventListener('click', () => ACWorkflow.preview ? location.replace('../') : ACAccountContext.signOutTo('customer-login/'));
  $('messageForm').addEventListener('submit', async event => { event.preventDefault(); const form = event.currentTarget, projectId = form.elements.project_id.value, body = form.elements.body.value.trim(); if (!projectId || !body) return; try { await ACWorkflow.sendMessage(projectId, body); form.elements.body.value = ''; data = await ACWorkflow.customerSnapshot(); render(); } catch (error) { $('alert').textContent = error.message; $('alert').hidden = false; } });
  async function start() {
    if (!ACWorkflow.preview && !(await ACAccountContext.guard('customer'))) return;
    const name = safeName(), email = safeEmail(); $('customerName').textContent = name; $('customerEmail').textContent = email; $('customerInitial').textContent = name[0].toUpperCase(); $('accountInitial').textContent = name[0].toUpperCase(); $('accountName').textContent = name; $('accountEmail').textContent = email;
    if (ACWorkflow.preview) document.querySelectorAll('#newRequestLink,#dashboardRequest,#requestsNew').forEach(link => link.href = '../request-job/?preview=1');
    try { data = await ACWorkflow.customerSnapshot(); render(); $('portal').hidden = false; } catch (error) { $('alert').textContent = error.message; $('alert').hidden = false; $('portal').hidden = false; }
  }
  start();
})();
