(function(){
  'use strict';
  const $=id=>document.getElementById(id);
  function message(text,type='error'){const box=$('message');box.textContent=text;box.className=`pa-message show ${type==='good'?'good':''}`}
  function clearMessage(){$('message').className='pa-message'}
  function setBusy(button,busy,label){button.disabled=busy;if(label)button.textContent=label}
  document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(item=>item.classList.toggle('active',item===button));['customerSignIn','customerSignUp'].forEach(id=>{$(id).hidden=id!==button.dataset.tab});clearMessage()}));
  $('customerSignIn').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter,original=button.textContent;setBusy(button,true,'Signing in…');try{await ACAuth.signIn($('signInEmail').value.trim(),$('signInPassword').value);if(!ACAuth.isCustomer()){location.replace(ACAccountContext.statusUrl(ACAuth.hasAccess()?'wrong_portal':'customer_account_required'));return}ACAccountContext.redirectAfterSignIn()}catch(error){message(error.message)}finally{setBusy(button,false,original)}});
  $('customerSignUp').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter,original=button.textContent;setBusy(button,true,'Creating account…');try{const data=await ACAuth.signUpCustomer($('signUpEmail').value.trim(),$('signUpPassword').value,$('fullName').value.trim());if(data.access_token&&ACAuth.isCustomer()){ACAccountContext.redirectAfterSignIn();return}message('Check your email and open the verification link. You will return to Customer Sign In.','good')}catch(error){message(error.message)}finally{setBusy(button,false,original)}});
  $('resetRequest').addEventListener('click',async()=>{const email=$('signInEmail').value.trim();if(!email)return message('Enter your customer email first.');try{await ACAuth.requestPasswordReset(email,'customer');message('Password reset email sent.','good')}catch(error){message(error.message)}});
  $('resendVerification').addEventListener('click',async()=>{const email=$('signUpEmail').value.trim();if(!email)return message('Enter your customer email first.');try{await ACAuth.resendVerification(email,'customer');message('Verification email sent again.','good')}catch(error){message(error.message)}});
  $('passwordForm').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter,original=button.textContent;setBusy(button,true,'Updating…');try{await ACAuth.updatePassword($('newPassword').value);$('newPassword').value='';message('Password updated successfully.','good');$('passwordForm').hidden=true}catch(error){message(error.message)}finally{setBusy(button,false,original)}});
  $('signOut').addEventListener('click',()=>ACAccountContext.signOutTo('customer-login/'));
  async function render(){await ACAuth.ready;const redirectType=sessionStorage.getItem('ac_auth_redirect_type')||'';sessionStorage.removeItem('ac_auth_redirect_type');if(redirectType==='recovery'){$('passwordForm').hidden=false;message('Secure recovery link accepted. Enter a new password.','good')}else if(redirectType)message('Email verified successfully.','good');if(!ACAuth.isSignedIn())return;if(ACAuth.isCustomer()){$('guestPanel').hidden=true;$('signedPanel').hidden=false;$('signedEmail').textContent=ACAuth.user()?.email||'Verified customer'}else location.replace(ACAccountContext.statusUrl(ACAuth.hasAccess()?'wrong_portal':'customer_account_required'))}
  render();
})();
