(function () {
  'use strict';
  const $ = id => document.getElementById(id);
  const app = $('app');
  const role = ACWorkflow.role();
  let state = null, selectedRequest = '', selectedProject = '', projectTab = 'overview';
  const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
  const nice = value => String(value || '—').replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
  const date = value => value ? new Date(value).toLocaleDateString('en-AU', { day: 'numeric', month: 'short', year: 'numeric' }) : '—';
  const dateTime = value => value ? new Date(value).toLocaleString('en-AU', { dateStyle: 'medium', timeStyle: 'short' }) : '—';
  const money = value => new Intl.NumberFormat('en-AU', { style: 'currency', currency: 'AUD' }).format(Number(value || 0));
  const member = id => state?.members?.find(item => item.id === id) || null;
  const memberName = id => member(id)?.full_name || member(id)?.email || 'Unassigned';
  const currentUser = () => {
    if (ACWorkflow.preview) return state?.members?.find(item => item.role === role) || { id: `${role}_demo`, full_name: nice(role), role };
    return { ...(ACAuth.profile() || {}), email: ACAuth.user()?.email || '' };
  };
  const projectById = id => state?.projects?.find(item => item.id === id);
  const statusTone = status => ['completed', 'approved', 'confirmed', 'accepted'].some(value => String(status).includes(value)) ? 'green' : ['delayed', 'not_suitable', 'rejected', 'cancelled'].some(value => String(status).includes(value)) ? 'red' : '';
  const statusBadge = status => `<span class="mg-status ${statusTone(status)}">${nice(status)}</span>`;
  const today = new Date().toISOString().slice(0, 10);

  function showAlert(message, good = false) { $('alert').textContent = message; $('alert').hidden = false; $('alert').style.borderColor = good ? 'var(--green)' : 'var(--red)'; $('alert').style.color = good ? 'var(--green)' : ''; setTimeout(() => { $('alert').hidden = true; }, 6500); }
  function preservePreview(path) { return ACWorkflow.preview ? `${path}${path.includes('?') ? '&' : '?'}preview=1&role=${encodeURIComponent(role)}` : path; }
  function view(name) {
    if (!ACWorkflow.can(name)) return showAlert(`${nice(role)} does not have access to ${nice(name)}.`);
    document.querySelectorAll('[data-panel]').forEach(node => node.classList.toggle('active', node.dataset.panel === name));
    document.querySelectorAll('[data-view]').forEach(node => node.classList.toggle('active', node.dataset.view === name));
    const labels = { dashboard: ['Management overview', 'Command Centre'], requests: ['Customer intake', 'New Requests'], projects: ['Project delivery', 'Projects'], inspections: ['Site verification', 'Site Inspections'], schedule: ['Delivery sequence', 'Schedule'], tasks: ['Assigned work', 'Tasks & Trades'], delays: ['Risk control', 'Delays & Follow-ups'], messages: ['Project communication', 'Messages'], team: ['People & access', 'Team Management'], timesheets: ['Daily accountability', 'My Day & Reports'], finance: ['Restricted commercial area', 'Finance'], reports: ['Oversight', 'Reports & Activity'], tools: ['Owner & Admin only', 'Professional Tools'] };
    $('pageKicker').textContent = labels[name]?.[0] || 'Management Portal'; $('pageTitle').textContent = labels[name]?.[1] || nice(name); app.classList.remove('side-open'); window.scrollTo({ top: 0, behavior: 'smooth' });
  }
  function applyPermissions() {
    document.querySelectorAll('[data-cap]').forEach(node => { node.hidden = !ACWorkflow.can(node.dataset.cap); });
    document.querySelectorAll('[data-operations-only]').forEach(node => { node.hidden = !ACWorkflow.canUseOperations(); });
    const labels = { owner: 'Owner', admin: 'Admin', manager: 'Manager', site_supervisor: 'Site Supervisor', worker: 'Worker / Tradie', estimator: 'Estimator' };
    $('roleLabel').textContent = labels[role] || nice(role); $('userRole').textContent = labels[role] || nice(role);
  }

  function renderDashboard() {
    const requests = state.requests || [], projects = visibleProjects(), tasks = visibleTasks(), reports = state.reports || [];
    const newRequests = requests.filter(item => ['new', 'admin_review'].includes(item.status)).length;
    const followups = requests.filter(item => ['follow_up_required', 'more_information_required'].includes(item.status)).length;
    const visits = projects.filter(item => ['site_inspection_assigned', 'inspection_completed'].includes(item.status)).length;
    const delayed = tasks.filter(item => item.status === 'delayed').length;
    $('kpiRequests').textContent = newRequests; $('kpiFollowups').textContent = followups; $('kpiVisits').textContent = visits; $('kpiDelays').textContent = delayed; $('kpiProjects').textContent = projects.filter(item => item.status !== 'completed').length; $('kpiReports').textContent = reports.filter(item => item.status === 'submitted').length;
    $('navRequestCount').textContent = newRequests; $('navRequestCount').hidden = !newRequests; $('navInspectionCount').textContent = visits; $('navInspectionCount').hidden = !visits; $('navDelayCount').textContent = delayed; $('navDelayCount').hidden = !delayed;
    const stages = [ ['New request', requests.filter(item => item.status === 'new').length], ['Admin review', requests.filter(item => ['admin_review', 'follow_up_required'].includes(item.status)).length], ['Site inspection', projects.filter(item => ['site_inspection_assigned', 'inspection_completed'].includes(item.status)).length], ['Estimate', projects.filter(item => ['estimate_preparation', 'quote_sent'].includes(item.status)).length], ['Scheduled', projects.filter(item => item.status === 'scheduled').length], ['In progress', projects.filter(item => item.status === 'in_progress').length], ['Completed', projects.filter(item => item.status === 'completed').length], ['Delayed tasks', delayed] ];
    $('pipeline').innerHTML = stages.map(([label, count]) => `<article><span>${label}</span><strong>${count}</strong><small>${count ? 'Open records' : 'Clear'}</small></article>`).join('');
    const alerts = [
      ...tasks.filter(item => item.status === 'delayed').map(item => ({ icon: '!', title: item.title, body: `${projectById(item.project_id)?.name || 'Project'} · trade delay`, view: 'delays' })),
      ...requests.filter(item => item.status === 'follow_up_required').map(item => ({ icon: '☎', title: `${item.customer_name} needs follow-up`, body: `${item.request_number} · ${item.phone}`, view: 'requests' })),
      ...reports.filter(item => item.status === 'submitted').map(item => ({ icon: '▤', title: 'Daily report awaiting review', body: `${memberName(item.user_id)} · ${date(item.report_date)}`, view: 'reports' }))
    ];
    $('priorityAlerts').innerHTML = alerts.length ? alerts.slice(0, 6).map(item => `<article class="mg-alert-row"><i>${item.icon}</i><div><strong>${escapeHtml(item.title)}</strong><span>${escapeHtml(item.body)}</span></div><button data-open="${item.view}">Open</button></article>`).join('') : '<div class="mg-empty"><b>✓</b><h3>No priority alert</h3><p>Every required next action is currently accounted for.</p></div>';
    renderActivity('activityFeed', (state.activities || []).slice(0, 8));
    document.querySelectorAll('#priorityAlerts [data-open]').forEach(button => button.addEventListener('click', () => view(button.dataset.open)));
    const roleCopy = { owner: 'Monitor the whole company: customer response, project risk, people, finance and approvals.', admin: 'Move each request and project to its next accountable owner without losing the customer history.', manager: 'Monitor project delivery, schedules, supervisors, delays and reporting.', site_supervisor: 'See assigned inspections, today’s trade plan, site risks and reports that must be submitted.', worker: 'See your assigned work, schedule and the daily report required before Clock Out.' };
    $('dashboardRoleCopy').textContent = roleCopy[role] || roleCopy.admin;
  }
  function renderActivity(target, entries) { $(target).innerHTML = entries.length ? entries.map(item => `<article><time>${dateTime(item.created_at)}</time><strong>${escapeHtml(item.description || nice(item.action))}</strong><span>${escapeHtml(memberName(item.actor_id))}</span></article>`).join('') : '<div class="mg-empty"><p>No recorded activity.</p></div>'; }

  function visibleProjects() { const list = state.projects || []; const user = currentUser(); if (['owner', 'admin', 'manager'].includes(role)) return list; if (role === 'site_supervisor') return list.filter(item => item.assigned_supervisor_id === user.id || item.assigned_supervisor_id === 'supervisor_demo'); return list.filter(project => (state.tasks || []).some(task => task.project_id === project.id && (task.assigned_to === user.id || task.assigned_to === 'worker_demo'))); }
  function visibleTasks() { const projects = new Set(visibleProjects().map(item => item.id)); const user = currentUser(); let tasks = (state.tasks || []).filter(item => projects.has(item.project_id)); if (role === 'worker') tasks = tasks.filter(item => item.assigned_to === user.id || item.assigned_to === 'worker_demo'); return tasks; }
  function renderRequests() {
    if (!ACWorkflow.can('requests')) return;
    const search = String($('requestSearch').value || '').toLowerCase(), status = $('requestStatus').value;
    const items = (state.requests || []).filter(item => (!status || item.status === status) && (!search || `${item.request_number} ${item.customer_name} ${item.suburb} ${(item.services || []).join(' ')}`.toLowerCase().includes(search)));
    $('requestList').innerHTML = items.length ? items.map(item => `<button class="mg-request-item ${selectedRequest === item.id ? 'active' : ''}" data-request="${item.id}"><div><h3>${escapeHtml(item.request_number)} · ${escapeHtml(item.customer_name)}</h3><p>${escapeHtml((item.services || []).join(', '))} · ${escapeHtml(item.suburb)}</p><small>Updated ${dateTime(item.updated_at || item.created_at)}</small></div>${statusBadge(item.status)}</button>`).join('') : '<div class="mg-empty"><h3>No matching requests</h3><p>Change the filters or wait for a new customer submission.</p></div>';
    document.querySelectorAll('[data-request]').forEach(button => button.addEventListener('click', () => { selectedRequest = button.dataset.request; renderRequests(); renderRequestDetail(); }));
    if (selectedRequest && !items.some(item => item.id === selectedRequest)) { selectedRequest = ''; renderRequestDetail(); }
  }
  function renderRequestDetail() {
    const item = state.requests.find(row => row.id === selectedRequest); if (!item) { $('requestDetail').innerHTML = '<div class="mg-empty"><b>＋</b><h3>Select a customer request</h3><p>Open a request to review contact information, files, scope, budget and next actions.</p></div>'; return; }
    const followups = (state.followups || []).filter(row => row.request_id === item.id);
    const linked = state.projects.find(project => project.request_id === item.id);
    $('requestDetail').innerHTML = `<div class="mg-detail-content"><header><div><span>${escapeHtml(item.request_number)}</span><h2>${escapeHtml(item.customer_name)}</h2><p>${escapeHtml(item.address)}, ${escapeHtml(item.suburb)} ${escapeHtml(item.state)} ${escapeHtml(item.postcode)}</p></div>${statusBadge(item.status)}</header><section class="mg-detail-section"><span>Customer &amp; location</span><div class="mg-detail-grid"><div><small>Phone</small><strong>${escapeHtml(item.phone)}</strong></div><div><small>Email</small><strong>${escapeHtml(item.email)}</strong></div><div><small>Preferred contact</small><strong>${escapeHtml(item.preferred_contact)}</strong></div><div><small>Property</small><strong>${escapeHtml(item.property_type)}</strong></div></div></section><section class="mg-detail-section"><span>Requested work</span><div class="mg-detail-grid"><div><small>Services</small><strong>${escapeHtml((item.services || []).join(', '))}</strong></div><div><small>Customer budget</small><strong>${escapeHtml(item.budget_range || 'Not provided')}</strong></div><div><small>Preferred start</small><strong>${date(item.preferred_start_date)}</strong></div><div><small>Urgency</small><strong>${item.urgent ? 'Urgent request' : 'Standard'}</strong></div></div><p class="mg-detail-text">${escapeHtml(item.description)}</p>${item.current_problem ? `<p class="mg-detail-text"><strong>Current problem:</strong> ${escapeHtml(item.current_problem)}</p>` : ''}${item.expected_result ? `<p class="mg-detail-text"><strong>Expected result:</strong> ${escapeHtml(item.expected_result)}</p>` : ''}</section><section class="mg-detail-section"><span>Follow-up history</span><div class="mg-followups">${followups.length ? followups.map(row => `<article><strong>${escapeHtml(row.outcome)} · ${escapeHtml(row.note)}</strong><span>${dateTime(row.created_at)} · next: ${escapeHtml(row.next_action || 'Not set')}</span></article>`).join('') : '<article><span>No contact recorded yet.</span></article>'}</div></section><footer class="mg-detail-actions"><button class="mg-btn" data-request-action="followup" data-id="${item.id}">Record Follow-up</button>${linked ? `<button class="mg-btn primary" data-open-project="${linked.id}">Open Project</button>` : `<button class="mg-btn primary" data-request-action="approve" data-id="${item.id}">Approve &amp; Create Project</button>`}</footer></div>`;
    $('requestDetail').querySelectorAll('[data-request-action]').forEach(button => button.addEventListener('click', () => button.dataset.requestAction === 'followup' ? openFollowup(button.dataset.id) : openApprove(button.dataset.id)));
    $('requestDetail').querySelectorAll('[data-open-project]').forEach(button => button.addEventListener('click', () => { view('projects'); openProject(button.dataset.openProject); }));
  }

  function renderProjects() {
    const search = String($('projectSearch').value || '').toLowerCase(), status = $('projectStatus').value;
    const projects = visibleProjects().filter(item => (!status || item.status === status) && (!search || `${item.project_number} ${item.name} ${item.address}`.toLowerCase().includes(search)));
    $('projectGrid').hidden = !!selectedProject; $('projectWorkspace').hidden = !selectedProject;
    $('projectGrid').innerHTML = projects.length ? projects.map(item => `<article class="mg-project-card" data-project="${item.id}"><header><span>${escapeHtml(item.project_number)}</span>${statusBadge(item.status)}</header><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.address)}</p><div class="mg-progress"><i style="width:${Number(item.progress || 0)}%"></i></div><footer><span>${Number(item.progress || 0)}% complete</span><span>${escapeHtml(memberName(item.assigned_supervisor_id))}</span></footer></article>`).join('') : '<div class="mg-empty"><h3>No matching projects</h3><p>No authorised project matches this filter.</p></div>';
    document.querySelectorAll('[data-project]').forEach(card => card.addEventListener('click', () => openProject(card.dataset.project)));
    if (selectedProject) renderProjectWorkspace();
  }
  function openProject(id) { selectedProject = id; projectTab = 'overview'; const workflowProject = projectById(id); if (workflowProject && window.ACProjects && ['owner','admin'].includes(role)) { let linked = ACProjects.list().find(item => item.notes?.includes(`workflow:${id}`) || item.name === workflowProject.name); if (!linked) linked = ACProjects.create({ name: workflowProject.name, category: workflowProject.services?.[0] || 'Construction', address: workflowProject.address, client: workflowProject.customer_name, status: workflowProject.status, notes: `workflow:${id}\n${workflowProject.admin_brief || ''}` }); ACProjects.setActive(linked.id); } renderProjects(); $('projectWorkspace').scrollIntoView({ block: 'start' }); }
  function projectTabs() {
    const tabs = [ ['overview', 'Overview'], ['workflow', 'Workflow'], ['customer', 'Customer'], ['inspection', 'Site Inspection'], ['schedule', 'Schedule'], ['tasks', 'Tasks & Trades'], ['messages', 'Messages'], ['notes', 'Notes'], ['documents', 'Documents'], ['photos', 'Photos'], ['activity', 'Activity Log'], ['reports', 'Reports'] ];
    if (['owner', 'admin'].includes(role)) tabs.splice(10, 0, ['quotes', 'Quotes & Estimates'], ['invoices', 'Invoices'], ['finance', 'Finance']);
    if (role === 'worker') return tabs.filter(([id]) => ['overview', 'schedule', 'tasks'].includes(id));
    if (role === 'site_supervisor') return tabs.filter(([id]) => !['customer', 'quotes', 'invoices', 'finance'].includes(id));
    return tabs;
  }
  function renderProjectWorkspace() {
    const project = projectById(selectedProject); if (!project) { selectedProject = ''; renderProjects(); return; }
    $('projectNumber').textContent = project.project_number; $('projectName').textContent = project.name; $('projectAddress').textContent = project.address; $('projectStatusBadge').className = `mg-status ${statusTone(project.status)}`; $('projectStatusBadge').textContent = nice(project.status);
    const tabs = projectTabs(); if (!tabs.some(([id]) => id === projectTab)) projectTab = tabs[0][0];
    $('projectTabs').innerHTML = tabs.map(([id, label]) => `<button class="${projectTab === id ? 'active' : ''}" data-project-tab="${id}">${label}</button>`).join('');
    $('projectTabs').querySelectorAll('button').forEach(button => button.addEventListener('click', () => { projectTab = button.dataset.projectTab; renderProjectWorkspace(); }));
    renderProjectTab(project);
  }
  function renderProjectTab(project) {
    const tasks = (state.tasks || []).filter(item => item.project_id === project.id), inspection = (state.inspections || []).find(item => item.project_id === project.id), notes = visibleNotes(project.id), delays = (state.delays || []).filter(item => item.project_id === project.id), reports = (state.reports || []).filter(item => item.project_id === project.id), quote = (state.quotes || []).find(item => item.project_id === project.id), messages = (state.messages || []).filter(item => item.project_id === project.id), documents = (state.documents || []).filter(item => item.project_id === project.id);
    const activity = (state.activities || []).filter(item => item.project_id === project.id);
    const templates = {
      overview: `<div class="mg-project-overview"><section><h3>Project summary</h3><div class="mg-detail-grid"><div><small>Customer status</small><strong>${nice(project.customer_status)}</strong></div><div><small>Progress</small><strong>${project.progress || 0}%</strong></div><div><small>Admin</small><strong>${escapeHtml(memberName(project.assigned_admin_id))}</strong></div><div><small>Site Supervisor</small><strong>${escapeHtml(memberName(project.assigned_supervisor_id))}</strong></div></div><h3 style="margin-top:20px">Admin Brief</h3><p>${escapeHtml(project.admin_brief || 'No brief recorded.')}</p></section><section><h3>Next accountable actions</h3><div class="mg-timeline">${tasks.slice(0, 5).map(task => `<article><i></i><div><strong>${escapeHtml(task.title)} · ${nice(task.status)}</strong><span>${date(task.start_date)} · ${escapeHtml(task.trade || '')}</span></div></article>`).join('') || '<p>No tasks scheduled.</p>'}</div></section></div>`,
      workflow: `<div class="mg-timeline">${[['Request approved', project.created_at], ['Site inspection', inspection?.submitted_at], ['Estimate & quote', quote?.created_at], ['Project scheduled', tasks[0]?.start_date], ['Work in progress', project.updated_at]].map(([label, when]) => `<article><i></i><div><strong>${label}</strong><span>${when ? dateTime(when) : 'Awaiting this stage'}</span></div></article>`).join('')}</div>`,
      customer: `<div class="mg-detail-grid"><div><small>Name</small><strong>${escapeHtml(project.customer_name)}</strong></div><div><small>Phone</small><strong>${escapeHtml(project.customer_phone)}</strong></div><div><small>Email</small><strong>${escapeHtml(project.customer_email)}</strong></div><div><small>Customer status</small><strong>${nice(project.customer_status)}</strong></div></div>`,
      inspection: inspection ? inspectionSummary(inspection) : `<div class="mg-empty"><h3>Inspection not submitted</h3><p>The assigned Site Supervisor can start and submit the inspection.</p>${ACWorkflow.can('inspections') ? `<button class="mg-btn primary" data-start-inspection="${project.id}">Start Site Inspection</button>` : ''}</div>`,
      schedule: `${['owner','admin','manager'].includes(role) ? `<div class="mg-page-actions" style="margin:0 0 14px"><button class="mg-btn primary" data-add-task="${project.id}">Add Task / Trade</button></div>` : ''}${scheduleHtml(tasks)}`,
      tasks: taskListHtml(tasks),
      messages: `<div class="mg-page-actions"><button class="mg-btn primary" data-message-project="${project.id}">Message Customer</button><a class="mg-btn" href="${preservePreview('../builder/?view=messages')}">Open Internal Team Chat</a></div><div class="mg-list" style="margin-top:15px">${messages.length ? messages.map(item => `<article class="mg-list-row"><div><h3>${item.sender_scope === 'customer' ? escapeHtml(project.customer_name) : 'Alert Construction team'}</h3><p>${escapeHtml(item.body)}</p><small>${dateTime(item.created_at)}</small></div></article>`).join('') : '<div class="mg-empty"><p>No customer-facing project messages yet.</p></div>'}</div>`,
      notes: `<div class="mg-page-actions"><button class="mg-btn primary" data-add-note="${project.id}">Add Note</button></div><div class="mg-list" style="margin-top:15px">${notes.length ? notes.map(note => `<article class="mg-list-row"><div><h3>${nice(note.visibility)}</h3><p>${escapeHtml(note.body)}</p><small>${dateTime(note.created_at)} · ${escapeHtml(memberName(note.created_by))}</small></div></article>`).join('') : '<div class="mg-empty"><p>No notes visible to this role.</p></div>'}</div>`,
      documents: `${['owner','admin'].includes(role) ? `<div class="mg-page-actions"><a class="mg-btn primary" href="${preservePreview('../builder/?view=documents')}">Open Secure File Workspace</a></div>` : ''}<div class="mg-list" style="margin-top:15px">${documents.length ? documents.map(item => `<article class="mg-list-row"><div><h3>${escapeHtml(item.file_name)}</h3><p>${escapeHtml(item.category || 'Project document')}</p><small>${item.customer_visible ? 'Shared with customer' : 'Internal only'} · ${date(item.created_at)}</small></div></article>`).join('') : '<div class="mg-empty"><p>No workflow documents registered for this project.</p></div>'}</div>`,
      photos: `<div class="mg-list">${documents.filter(item => /^image\//.test(item.mime_type || '')).length ? documents.filter(item => /^image\//.test(item.mime_type || '')).map(item => `<article class="mg-list-row"><div><h3>${escapeHtml(item.file_name)}</h3><p>${escapeHtml(item.category || 'Site photo')}</p><small>${item.customer_visible ? 'Shared with customer' : 'Internal only'} · ${date(item.created_at)}</small></div></article>`).join('') : '<div class="mg-empty"><h3>No site photos yet</h3><p>Site Supervisors can attach photos when submitting an inspection.</p></div>'}</div>`,
      quotes: `<div class="mg-page-actions"><button class="mg-btn primary" data-save-quote="${project.id}">${quote ? 'Edit / Share Quote' : 'Create Project Quote'}</button><a class="mg-btn" href="${preservePreview('../quote-analysis/')}">Open Estimate Tools</a></div>${quote ? `<div class="mg-list-row" style="margin-top:15px"><div><h3>${escapeHtml(quote.quote_number)} · ${escapeHtml(quote.title)}</h3><p>Total ${money(quote.total)} · valid until ${date(quote.valid_until)}</p><small>${nice(quote.status)} · ${quote.customer_visible ? 'Shared with customer' : 'Internal draft'}</small></div><aside>${statusBadge(quote.status)}</aside></div>` : '<div class="mg-empty" style="margin-top:15px"><h3>No project quote yet</h3><p>Use an internal estimator or enter the approved project total here.</p></div>'}`,
      invoices: `<div class="mg-link-grid"><a href="${preservePreview('../invoice/')}"><b>I</b><h3>Project Invoices</h3><p>Create or review invoices linked to this project.</p><strong>Open Invoice Generator →</strong></a></div>`,
      finance: `<div class="mg-link-grid"><a href="${preservePreview('../builder/?view=financial-data')}"><b>$</b><h3>Project Finance</h3><p>Review authorised budget, costs, payments, forecast and variance.</p><strong>Open restricted Finance →</strong></a></div>`,
      activity: `<div class="mg-activity">${activity.map(item => `<article><time>${dateTime(item.created_at)}</time><strong>${escapeHtml(item.description || nice(item.action))}</strong><span>${escapeHtml(memberName(item.actor_id))}</span></article>`).join('') || '<div class="mg-empty"><p>No activity recorded.</p></div>'}</div>`,
      reports: `<div class="mg-list">${reports.length ? reports.map(reportRow).join('') : '<div class="mg-empty"><p>No daily reports for this project.</p></div>'}</div>`
    };
    $('projectTabContent').innerHTML = templates[projectTab] || '<div class="mg-empty"><p>This tab is not available.</p></div>';
    $('projectTabContent').querySelectorAll('[data-start-inspection]').forEach(button => button.addEventListener('click', () => openInspection(button.dataset.startInspection)));
    $('projectTabContent').querySelectorAll('[data-add-note]').forEach(button => button.addEventListener('click', () => openNote(button.dataset.addNote)));
    $('projectTabContent').querySelectorAll('[data-add-task]').forEach(button => button.addEventListener('click', () => openTask(button.dataset.addTask)));
    $('projectTabContent').querySelectorAll('[data-save-quote]').forEach(button => button.addEventListener('click', () => openQuote(button.dataset.saveQuote)));
    $('projectTabContent').querySelectorAll('[data-message-project]').forEach(button => button.addEventListener('click', async () => { const body = prompt('Customer-facing project message'); if (!body?.trim()) return; try { await ACWorkflow.sendMessage(button.dataset.messageProject, body.trim()); await reload('Customer message sent.'); projectTab = 'messages'; renderProjectWorkspace(); } catch (error) { showAlert(error.message); } }));
    bindTaskActions($('projectTabContent'));
  }
  function visibleNotes(projectId) { const allowed = role === 'owner' || role === 'admin' || role === 'manager' ? ['private_management', 'supervisor', 'team', 'customer'] : role === 'site_supervisor' ? ['supervisor', 'team', 'customer'] : ['team']; return (state.notes || []).filter(item => item.project_id === projectId && allowed.includes(item.visibility)); }
  function inspectionSummary(item) { const areas = (state.areas || []).filter(area => area.inspection_id === item.id); return `<div class="mg-detail-grid"><div><small>Visit</small><strong>${date(item.visit_date)} · ${escapeHtml(item.arrival_time)}–${escapeHtml(item.departure_time)}</strong></div><div><small>Status</small><strong>${nice(item.status)}</strong></div><div><small>Site access</small><strong>${escapeHtml(item.site_access || '—')}</strong></div><div><small>Safety</small><strong>${escapeHtml(item.safety_issues || 'None recorded')}</strong></div><div><small>Required trades</small><strong>${escapeHtml((item.trades_required || []).join(', '))}</strong></div><div><small>Risks</small><strong>${escapeHtml(item.risks || 'None recorded')}</strong></div></div><p class="mg-detail-text"><strong>Work required:</strong> ${escapeHtml(item.work_required || '')}</p><p class="mg-detail-text"><strong>Recommended sequence:</strong> ${escapeHtml(item.recommended_sequence || '')}</p>${areas.map(area => `<section class="mg-detail-section"><span>${escapeHtml(area.area_name)}</span><div class="mg-detail-grid"><div><small>Dimensions</small><strong>${area.length || '—'} × ${area.width || '—'} × ${area.height || '—'} m</strong></div><div><small>Floor area</small><strong>${area.floor_area || '—'} m²</strong></div><div><small>Issues</small><strong>${escapeHtml(area.issues || '—')}</strong></div><div><small>Required work</small><strong>${escapeHtml(area.required_work || '—')}</strong></div></div></section>`).join('')}`; }
  function scheduleHtml(tasks) { return `<div class="mg-schedule"><table class="mg-table"><thead><tr><th>Date</th><th>Activity</th><th>Trade / Responsible</th><th>Status</th><th>Action</th></tr></thead><tbody>${tasks.map(task => `<tr><td>${date(task.start_date)}</td><td>${escapeHtml(task.title)}</td><td>${escapeHtml(task.trade || memberName(task.assigned_to))}</td><td>${statusBadge(task.status)}</td><td>${['owner', 'admin', 'manager', 'site_supervisor'].includes(role) ? `<button data-task-delay="${task.id}">Record delay</button>` : 'View only'}</td></tr>`).join('')}</tbody></table></div>`; }
  function taskListHtml(tasks) { return `<div class="mg-list">${tasks.map(task => `<article class="mg-list-row"><div><h3>${escapeHtml(task.title)} · ${escapeHtml(task.trade || '')}</h3><p>${date(task.start_date)} to ${date(task.due_date)}</p><small>${nice(task.status)}</small></div><aside>${['owner', 'admin', 'manager', 'site_supervisor', 'worker'].includes(role) ? `<button class="mg-btn" data-task-complete="${task.id}">Mark Completed</button>` : ''}</aside></article>`).join('') || '<div class="mg-empty"><p>No tasks scheduled.</p></div>'}</div>`; }

  function renderInspections() { const projects = visibleProjects(); $('inspectionGrid').innerHTML = projects.map(project => { const item = state.inspections.find(row => row.project_id === project.id); return `<article class="mg-inspection-card"><span>${escapeHtml(project.project_number)}</span><h3>${escapeHtml(project.name)}</h3><p>${item ? `Submitted ${dateTime(item.submitted_at)}` : `Assigned to ${escapeHtml(memberName(project.assigned_supervisor_id))}`}</p><footer>${item ? statusBadge(item.status) : `<button class="mg-btn primary" data-start-inspection="${project.id}">Start Site Inspection</button>`}<button class="mg-btn" data-open-project="${project.id}">Open Project</button></footer></article>`; }).join('') || '<div class="mg-empty"><p>No assigned site inspections.</p></div>'; document.querySelectorAll('[data-start-inspection]').forEach(button => button.addEventListener('click', () => openInspection(button.dataset.startInspection))); document.querySelectorAll('#inspectionGrid [data-open-project]').forEach(button => button.addEventListener('click', () => { view('projects'); openProject(button.dataset.openProject); })); }
  function renderSchedule() { $('scheduleTable').innerHTML = scheduleHtml(visibleTasks()); bindTaskActions($('scheduleTable')); }
  function renderTasks() { const groups = [ ['not_started', 'Not Started'], ['confirmed', 'Confirmed / On Site'], ['in_progress', 'In Progress'], ['completed', 'Completed'] ]; const tasks = visibleTasks(); $('taskBoard').innerHTML = groups.map(([status, label]) => { const list = status === 'confirmed' ? tasks.filter(item => ['confirmed', 'on_site'].includes(item.status)) : tasks.filter(item => item.status === status || (status === 'not_started' && item.status === 'delayed')); return `<section class="mg-task-column"><header><span>${label}</span><b>${list.length}</b></header>${list.map(item => `<article class="mg-task-card"><strong>${escapeHtml(item.title)}</strong><span>${escapeHtml(projectById(item.project_id)?.name || '')}</span><small>${escapeHtml(item.trade || '')} · ${date(item.due_date)} · ${nice(item.status)}</small><footer><button data-task-complete="${item.id}">Complete</button><button data-task-delay="${item.id}">Delay</button></footer></article>`).join('')}</section>`; }).join(''); bindTaskActions($('taskBoard')); }
  function bindTaskActions(root) { root.querySelectorAll('[data-task-complete]').forEach(button => button.addEventListener('click', () => completeTask(button.dataset.taskComplete))); root.querySelectorAll('[data-task-delay]').forEach(button => button.addEventListener('click', () => { const task = state.tasks.find(item => item.id === button.dataset.taskDelay); openDelay(task.project_id, task.id); })); }
  async function completeTask(id) { try { await ACWorkflow.updateTask(id, 'completed'); await reload('Task marked completed.'); } catch (error) { showAlert(error.message); } }
  function renderDelays() { const projects = new Set(visibleProjects().map(item => item.id)); const delays = state.delays.filter(item => projects.has(item.project_id)); $('delayList').innerHTML = delays.length ? delays.map(item => `<article class="mg-list-row"><div><h3>${escapeHtml(state.tasks.find(task => task.id === item.task_id)?.title || 'Project delay')}</h3><p>${escapeHtml(item.reason)}</p><small>Contacted ${escapeHtml(item.person_contacted)} · new expected date ${date(item.new_expected_date)} · impact: ${escapeHtml(item.impact || 'Not recorded')}</small><p><strong>Customer update:</strong> ${escapeHtml(item.customer_update)}</p></div><aside><strong>${escapeHtml(projectById(item.project_id)?.project_number || '')}</strong><span>${dateTime(item.created_at)}</span></aside></article>`).join('') : '<div class="mg-empty"><b>✓</b><h3>No recorded delays</h3><p>No assigned project currently has a delay record.</p></div>'; }
  function renderTeam() { $('teamGrid').innerHTML = state.members.filter(item => item.active).map(item => `<article class="mg-team-card"><span>${nice(item.role)}</span><h3>${escapeHtml(item.full_name || item.email)}</h3><p>${escapeHtml(item.email)}</p>${statusBadge(item.active ? 'active' : 'inactive')}</article>`).join(''); }
  function reportRow(item) { const actions = role === 'owner' && ['submitted','supervisor_verified','changes_requested'].includes(item.status) ? `<button class="mg-btn" data-report-action="approved" data-report="${item.id}">Approve</button><button class="mg-btn danger" data-report-action="changes_requested" data-report="${item.id}">Request Changes</button>` : role === 'site_supervisor' && item.status === 'submitted' ? `<button class="mg-btn" data-report-action="supervisor_verified" data-report="${item.id}">Verify Work</button>` : ''; return `<article class="mg-list-row"><div><h3>${escapeHtml(memberName(item.user_id))} · ${escapeHtml(projectById(item.project_id)?.name || 'Project')}</h3><p><strong>Completed:</strong> ${escapeHtml(item.completed)}</p><p><strong>Unfinished:</strong> ${escapeHtml(item.unfinished)}</p><small>${date(item.report_date)} · ${nice(item.status)}</small></div><aside>${statusBadge(item.status)}${actions}</aside></article>`; }
  function bindReportActions(root) { root.querySelectorAll('[data-report-action]').forEach(button => button.addEventListener('click', async () => { const note = button.dataset.reportAction === 'changes_requested' ? prompt('What needs to be changed?') : ''; if (button.dataset.reportAction === 'changes_requested' && !note) return; try { await ACWorkflow.reviewDailyReport(button.dataset.report, button.dataset.reportAction, note || ''); await reload('Daily report review saved.'); } catch (error) { showAlert(error.message); } })); }
  function renderReports() { $('reportList').innerHTML = state.reports.filter(item => ['submitted','supervisor_verified'].includes(item.status)).map(reportRow).join('') || '<div class="mg-empty"><p>No reports awaiting review.</p></div>'; $('allReports').innerHTML = state.reports.map(reportRow).join('') || '<div class="mg-empty"><p>No reports submitted.</p></div>'; bindReportActions($('reportList')); bindReportActions($('allReports')); renderActivity('allActivity', state.activities.slice(0, 30)); }
  function renderDay() { const options = visibleProjects().map(project => `<option value="${project.id}">${escapeHtml(project.name)}</option>`).join(''); $('clockProject').innerHTML = options; $('dailyReportForm').elements.project_id.innerHTML = options; const clock = (state.time_entries || []).find(item => item.user_id === currentUser().id && !item.clocked_out_at); if (clock) { $('clockStatus').textContent = 'Clocked In'; $('clockMeta').textContent = `${dateTime(clock.clocked_in_at)} · ${escapeHtml(projectById(clock.project_id)?.name || '')}`; $('clockButton').textContent = 'Clocked In'; $('clockButton').disabled = true; $('dailyReportForm').elements.project_id.value = clock.project_id; } else { $('clockStatus').textContent = 'Not clocked in'; $('clockMeta').textContent = 'Select a project and start your day.'; $('clockButton').textContent = 'Clock In'; $('clockButton').disabled = false; } }
  function renderNotifications() { const user = currentUser(), items = (state.notifications || []).filter(item => !item.recipient_id || item.recipient_id === user.id || item.recipient_id === `${role}_demo`); $('notificationCount').textContent = items.filter(item => !item.read_at).length; }
  function renderAll() { renderDashboard(); renderRequests(); renderRequestDetail(); renderProjects(); renderInspections(); renderSchedule(); renderTasks(); renderDelays(); renderTeam(); renderDay(); renderReports(); renderNotifications(); }

  function openFollowup(id) { $('followupForm').reset(); $('followupForm').elements.request_id.value = id; $('followupDialog').showModal(); }
  function openApprove(id) { $('approveForm').reset(); $('approveForm').elements.request_id.value = id; $('approveForm').elements.supervisor_id.innerHTML = state.members.filter(item => item.role === 'site_supervisor' && item.active).map(item => `<option value="${item.id}">${escapeHtml(item.full_name || item.email)}</option>`).join(''); $('approveDialog').showModal(); }
  function openInspection(id) { const project = projectById(id); if (!project) return; $('inspectionForm').reset(); $('inspectionForm').elements.project_id.value = id; $('inspectionForm').elements.visit_date.value = today; $('inspectionDialog').showModal(); }
  function openDelay(projectId, taskId) { $('delayForm').reset(); $('delayForm').elements.project_id.value = projectId; $('delayForm').elements.task_id.value = taskId; $('delayForm').elements.contact_time.value = new Date(Date.now() - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, 16); $('delayDialog').showModal(); }
  function openTask(projectId) { $('taskForm').reset(); $('taskForm').elements.project_id.value = projectId; $('taskForm').elements.start_date.value = today; $('taskForm').elements.due_date.value = today; $('taskForm').elements.assigned_to.innerHTML = '<option value="">External trade / unassigned</option>' + state.members.filter(item => item.active && ['site_supervisor','worker'].includes(item.role)).map(item => `<option value="${item.id}">${escapeHtml(item.full_name || item.email)} · ${nice(item.role)}</option>`).join(''); $('taskDialog').showModal(); }
  function openNote(projectId) { $('noteForm').reset(); $('noteForm').elements.project_id.value = projectId; if (role === 'site_supervisor') $('noteForm').elements.visibility.querySelector('option[value="private_management"]')?.remove(); $('noteDialog').showModal(); }
  function openQuote(projectId) { if (!['owner','admin'].includes(role)) return showAlert('Only Owner or Admin can create a quote.'); const form = $('quoteForm'), project = projectById(projectId), quote = (state.quotes || []).find(item => item.project_id === projectId); form.reset(); form.elements.project_id.value = projectId; form.elements.id.value = quote?.id || ''; form.elements.quote_number.value = quote?.quote_number || `QUO-${String(project?.project_number || '').replace('ATP-P-', '')}`; form.elements.title.value = quote?.title || project?.name || ''; form.elements.subtotal.value = quote?.subtotal || ''; form.elements.gst.value = quote?.gst || ''; form.elements.total.value = quote?.total || ''; form.elements.valid_until.value = quote?.valid_until || new Date(Date.now() + 30 * 86400000).toISOString().slice(0, 10); form.elements.source_tool.value = quote?.source_tool || 'Custom Estimate'; form.elements.share_with_customer.checked = Boolean(quote?.customer_visible); $('quoteDialog').showModal(); }
  function formObject(form) { return Object.fromEntries(new FormData(form).entries()); }
  $('followupForm').addEventListener('submit', async event => { event.preventDefault(); const data = formObject(event.currentTarget); try { await ACWorkflow.recordFollowup(data.request_id, { outcome: data.outcome, note: data.note, next_action: data.next_action, due_at: data.due_at ? new Date(data.due_at).toISOString() : null, status: data.outcome }); $('followupDialog').close(); await reload('Customer follow-up saved.'); } catch (error) { showAlert(error.message); } });
  $('approveForm').addEventListener('submit', async event => { event.preventDefault(); const data = formObject(event.currentTarget); try { const project = await ACWorkflow.approveRequest(data.request_id, { supervisor_id: data.supervisor_id, admin_brief: data.admin_brief, site_visit_at: new Date(data.site_visit_at).toISOString() }); $('approveDialog').close(); await reload('Project created and Site Supervisor notified.'); view('projects'); openProject(project.id); } catch (error) { showAlert(error.message); } });
  $('inspectionForm').addEventListener('submit', async event => { event.preventDefault(); const form = event.currentTarget, data = formObject(form), files = [...(form.elements.inspection_files.files || [])], length = Number(data.length || 0), width = Number(data.width || 0), height = Number(data.height || 0); try { await ACWorkflow.submitInspection(data.project_id, { visit_date: data.visit_date, arrival_time: data.arrival_time, departure_time: data.departure_time, customer_present: data.customer_present === 'true', weather: data.weather, site_access: data.site_access, parking_access: data.parking_access, safety_issues: data.safety_issues, risks: data.risks, work_required: data.work_required, materials_required: data.materials_required, trades_required: data.trades_required.split(',').map(value => value.trim()).filter(Boolean), recommended_sequence: data.recommended_sequence, customer_decisions: data.customer_decisions, areas: [{ area_name: data.area_name, length, width, height, floor_area: length && width ? Number((length * width).toFixed(2)) : null, wall_area: length && width && height ? Number((2 * (length + width) * height).toFixed(2)) : null, existing_fixtures: data.existing_fixtures, demolition_required: data.demolition_required === 'true', issues: data.area_issues, required_work: data.area_required_work }] }); for (const file of files) await ACWorkflow.uploadProjectDocument(data.project_id, file, 'Site inspection', false); $('inspectionDialog').close(); await reload(`Inspection submitted to Admin${files.length ? ` with ${files.length} file${files.length === 1 ? '' : 's'}` : ''}.`); } catch (error) { showAlert(error.message); } });
  $('delayForm').addEventListener('submit', async event => { event.preventDefault(); const data = formObject(event.currentTarget); try { await ACWorkflow.recordDelay(data.project_id, data.task_id, { reason: data.reason, person_contacted: data.person_contacted, contact_time: new Date(data.contact_time).toISOString(), new_expected_date: data.new_expected_date, impact: data.impact, internal_note: data.internal_note, customer_update: data.customer_update }); $('delayDialog').close(); await reload('Delay recorded and Admin notified.'); view('delays'); } catch (error) { showAlert(error.message); } });
  $('taskForm').addEventListener('submit', async event => { event.preventDefault(); const data = formObject(event.currentTarget); try { await ACWorkflow.createTask(data.project_id, { title: data.title, trade: data.trade, assigned_to: data.assigned_to || null, start_date: data.start_date, due_date: data.due_date, status: data.status, customer_visible: event.currentTarget.elements.customer_visible.checked }); $('taskDialog').close(); await reload('Schedule task created.'); projectTab = 'schedule'; renderProjectWorkspace(); } catch (error) { showAlert(error.message); } });
  $('noteForm').addEventListener('submit', async event => { event.preventDefault(); const data = formObject(event.currentTarget); try { await ACWorkflow.addNote(data.project_id, data.visibility, data.body); $('noteDialog').close(); await reload('Project note saved with the selected visibility.'); } catch (error) { showAlert(error.message); } });
  $('quoteForm').addEventListener('submit', async event => { event.preventDefault(); const data = formObject(event.currentTarget); try { await ACWorkflow.saveQuote(data.project_id, { id: data.id || null, quote_number: data.quote_number, title: data.title, subtotal: Number(data.subtotal), gst: Number(data.gst), total: Number(data.total), valid_until: data.valid_until, source_tool: data.source_tool, share_with_customer: event.currentTarget.elements.share_with_customer.checked }); $('quoteDialog').close(); await reload(event.currentTarget.elements.share_with_customer.checked ? 'Quote shared with the Customer Portal.' : 'Internal quote saved.'); projectTab = 'quotes'; renderProjectWorkspace(); } catch (error) { showAlert(error.message); } });
  $('dailyReportForm').addEventListener('submit', async event => { event.preventDefault(); const data = formObject(event.currentTarget); if (!data.completed || !data.unfinished || !data.tomorrow) return showAlert('Completed work, unfinished work and tomorrow’s work are required before Clock Out.'); try { await ACWorkflow.submitDailyReport(data.project_id, data); event.currentTarget.reset(); await reload('Daily report submitted and Clock Out completed.'); } catch (error) { showAlert(error.message); } });
  $('clockButton').addEventListener('click', async () => { const projectId = $('clockProject').value; if (!projectId) return showAlert('Choose a project before Clock In.'); try { await ACWorkflow.clockIn(projectId); await reload('Clock In recorded.'); } catch (error) { showAlert(error.message); } });

  $('closeProject').addEventListener('click', () => { selectedProject = ''; renderProjects(); });
  ['requestSearch', 'requestStatus'].forEach(id => $(id).addEventListener('input', renderRequests)); ['projectSearch', 'projectStatus'].forEach(id => $(id).addEventListener('input', renderProjects));
  document.querySelectorAll('[data-view]').forEach(button => button.addEventListener('click', () => view(button.dataset.view))); document.querySelectorAll('[data-open]').forEach(button => button.addEventListener('click', () => view(button.dataset.open)));
  $('menu').addEventListener('click', () => app.classList.toggle('side-open')); $('backdrop').addEventListener('click', () => app.classList.remove('side-open'));
  $('refresh').addEventListener('click', () => reload('Workflow refreshed.')); $('signOut').addEventListener('click', () => ACWorkflow.preview ? location.replace('../') : ACAccountContext.signOutTo('team-login/'));
  $('previewRole').addEventListener('change', event => { const url = new URL(location.href); url.searchParams.set('preview', '1'); url.searchParams.set('role', event.target.value); location.href = url.href; });
  async function reload(message = '') { state = await ACWorkflow.managementSnapshot(); renderAll(); if (message) showAlert(message, true); }
  async function start() {
    if (!ACWorkflow.preview && !(await ACAccountContext.guard('management'))) return;
    if (!['owner', 'admin', 'manager', 'site_supervisor', 'worker', 'estimator'].includes(role)) { location.replace(ACAccountContext.statusUrl('management_required')); return; }
    applyPermissions();
    if (ACWorkflow.preview) { $('previewRoleWrap').hidden = false; $('previewRole').value = role; document.querySelectorAll('a[href^="../"]').forEach(link => { if (!link.href.includes('/management/')) link.href = preservePreview(link.getAttribute('href')); }); }
    try { state = await ACWorkflow.managementSnapshot(); const user = currentUser(); $('userName').textContent = user.full_name || user.email || nice(role); $('userInitial').textContent = String(user.full_name || user.email || role)[0].toUpperCase(); $('todayLabel').textContent = new Date().toLocaleDateString('en-AU', { weekday: 'long', day: 'numeric', month: 'long' }); renderAll(); app.hidden = false; } catch (error) { app.hidden = false; showAlert(error.message); }
  }
  start();
})();
