/* eslint-disable @typescript-eslint/no-explicit-any */
type Role = "owner" | "admin" | "supervisor";
type DemoState = { cases: any[]; events: any[]; supervisors: Array<{ email: string; name: string }>; nextId: number };
const key = "atp-v65-workflow-demo";
const now = "2026-08-10T16:30:00+10:00";

const initial: DemoState = {
  nextId: 40,
  supervisors: [{ email: "site.supervisor@alerttradiepro.demo", name: "Site Supervisor 01" }],
  cases: [
    { id: 1, requestCode: "REQ-2026-0201", projectCode: "ATP-2026-00201", customerName: "Demo Customer", customerEmail: "customer@example.com", customerPhone: "0400 000 201", service: "Home Extension", suburb: "Glen Waverley", description: "Ground-floor family room extension and internal reconfiguration.", timeframe: "Within 1–3 months", budget: "$150,000–$300,000", stage: "site_visit_scheduled", assignedSupervisorEmail: "site.supervisor@alerttradiepro.demo", assignedSupervisorName: "Site Supervisor 01", siteVisitAt: "2026-08-12T09:30:00+10:00", projectFolder: "projects/ATP-2026-00201", createdAt: now, updatedAt: now, visitReport: null, estimate: null, files: [], updates: [] },
    { id: 2, requestCode: "REQ-2026-0198", projectCode: "ATP-2026-00198", customerName: "Demo Customer 198", customerEmail: "customer198@example.com", customerPhone: "0400 000 198", service: "Home Renovation", suburb: "Rowville", description: "Ground-floor renovation and service upgrades.", timeframe: "Within 3–6 months", budget: "$75,000–$150,000", stage: "active_project", assignedSupervisorEmail: "site.supervisor@alerttradiepro.demo", assignedSupervisorName: "Site Supervisor 01", siteVisitAt: "2026-07-28T10:00:00+10:00", projectFolder: "projects/ATP-2026-00198", createdAt: now, updatedAt: now, visitReport: { id: 3, caseId: 2, supervisorEmail: "site.supervisor@alerttradiepro.demo", visitDate: "2026-07-28", summary: "Site measured and access confirmed.", findings: "Existing services recorded and framing areas photographed.", recommendations: "Proceed with estimate and staged delivery.", internalNotes: "", status: "approved", adminNote: "Approved", submittedAt: now, reviewedAt: now }, estimate: { id: 4, caseId: 2, amountCents: 12850000, scope: "Ground-floor renovation, plumbing and electrical upgrades, finishes and project management.", terms: "Subject to final selections and contract.", status: "customer_accepted", createdBy: "admin@alerttradiepro.demo", createdAt: now, sentAt: now, customerDecidedAt: now, confirmedAt: now }, files: [], updates: [{ id: 5, caseId: 2, workDate: "2026-08-10", supervisorEmail: "site.supervisor@alerttradiepro.demo", internalUpdate: "Framing dimensions checked. Plumbing set-out ready. No safety issues recorded.", customerUpdate: "Framing checks are complete and the area is ready for the plumbing rough-in.", status: "pending_admin", adminNote: "", ownerNote: "", createdAt: now, adminReviewedAt: "", ownerReviewedAt: "", publishedAt: "", files: [] }] },
  ],
  events: [
    { id: 10, caseId: 2, actorRole: "Site Supervisor", actorEmail: "site.supervisor@alerttradiepro.demo", eventType: "progress_update_submitted", title: "A progress update is waiting for Admin", detail: "Customer copy remains hidden until Admin and Owner approve it.", audience: "internal", createdAt: now },
    { id: 9, caseId: 2, actorRole: "Admin", actorEmail: "admin@alerttradiepro.demo", eventType: "project_activated", title: "Customer-approved estimate converted to an active project", detail: "ATP-2026-00198", audience: "internal", createdAt: now },
    { id: 8, caseId: 1, actorRole: "Admin", actorEmail: "admin@alerttradiepro.demo", eventType: "site_visit_assigned", title: "Site visit assigned to Site Supervisor 01", detail: "12 August 2026 · 9:30 am", audience: "internal", createdAt: now },
  ],
};

function clone<T>(value: T): T { return JSON.parse(JSON.stringify(value)) as T; }
function load(): DemoState { try { return JSON.parse(localStorage.getItem(key) ?? "") as DemoState; } catch { return clone(initial); } }
function save(state: DemoState) { localStorage.setItem(key, JSON.stringify(state)); }
function json(data: unknown, status = 200) { return new Response(JSON.stringify(data), { status, headers: { "Content-Type": "application/json" } }); }
function event(state: DemoState, caseId: number, role: string, type: string, title: string, detail = "", audience = "internal") { state.events.unshift({ id: state.nextId++, caseId, actorRole: role, actorEmail: `${role.toLowerCase().replaceAll(" ", ".")}@alerttradiepro.demo`, eventType: type, title, detail, audience, createdAt: new Date().toISOString() }); }
function snapshot(state: DemoState, role: Role) { const cases = role === "supervisor" ? state.cases.filter((item) => item.assignedSupervisorEmail === "site.supervisor@alerttradiepro.demo").map((item) => ({ ...item, customerEmail: "", customerPhone: "", budget: "", estimate: null })) : state.cases; return { cases, events: state.events.filter((item) => cases.some((entry) => entry.id === item.caseId)), supervisors: state.supervisors, role }; }
function publicData(item: any, state: DemoState) { return { id: item.id, requestCode: item.requestCode, projectCode: item.projectCode, service: item.service, suburb: item.suburb, stage: item.stage, siteVisitAt: item.siteVisitAt, updatedAt: item.updatedAt, estimate: item.estimate && ["sent", "customer_accepted", "customer_declined"].includes(item.estimate.status) ? item.estimate : null, updates: item.updates.filter((update: any) => update.status === "published").map((update: any) => ({ ...update, files: update.files.filter((file: any) => file.visibility === "published") })), activity: state.events.filter((entry) => entry.caseId === item.id && entry.audience === "customer").map(({ title, detail, createdAt }) => ({ title, detail, createdAt })) }; }

async function readFile(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(reader.error); reader.readAsDataURL(file); }); }

function perform(state: DemoState, role: Role, action: string, caseId: number, payload: any) {
  const item = state.cases.find((entry) => entry.id === caseId); if (!item) throw new Error("Project workflow was not found."); const stamp = new Date().toISOString();
  if (action === "review_started") { item.stage = "admin_review"; event(state, caseId, "Admin", action, "Admin started reviewing the customer request"); }
  else if (action === "customer_contacted") { item.stage = "customer_contacted"; event(state, caseId, "Admin", action, "Admin contacted the customer", payload.note); }
  else if (action === "approve_intake") { item.stage = "site_visit_ready"; item.projectCode ||= item.requestCode.replace("REQ", "ATP"); item.projectFolder = `projects/${item.projectCode}`; event(state, caseId, "Admin", action, "Admin approved intake and created the project folder", item.projectFolder); }
  else if (action === "assign_visit") { item.stage = "site_visit_scheduled"; item.assignedSupervisorEmail = payload.supervisorEmail; item.assignedSupervisorName = payload.supervisorName; item.siteVisitAt = payload.visitAt; event(state, caseId, "Admin", action, `Site visit assigned to ${payload.supervisorName}`, payload.visitAt); }
  else if (action === "submit_site_visit") { if (!payload.fileIds?.length) throw new Error("At least one site photo is required."); item.stage = "site_visit_submitted"; item.visitReport = { id: state.nextId++, caseId, supervisorEmail: "site.supervisor@alerttradiepro.demo", ...payload, status: "submitted", adminNote: "", submittedAt: stamp, reviewedAt: "" }; event(state, caseId, "Site Supervisor", action, "Site visit report and photos submitted to Admin", `${payload.fileIds.length} photo(s) attached.`); }
  else if (action === "review_site_visit") { item.visitReport.status = payload.decision; item.visitReport.adminNote = payload.note; item.stage = payload.decision === "approved" ? "site_visit_approved" : "visit_changes_requested"; event(state, caseId, "Admin", action, payload.decision === "approved" ? "Admin approved the site visit report" : "Admin returned the site visit report", payload.note); }
  else if (action === "save_estimate") { item.stage = "estimate_ready"; item.estimate = { id: state.nextId++, caseId, amountCents: Math.round(Number(payload.amount) * 100), scope: payload.scope, terms: payload.terms, status: "draft", createdBy: "admin@alerttradiepro.demo", createdAt: stamp, sentAt: "", customerDecidedAt: "", confirmedAt: "" }; event(state, caseId, "Admin", action, "Admin prepared the estimate"); }
  else if (action === "send_estimate") { item.stage = "estimate_sent"; item.estimate.status = "sent"; item.estimate.sentAt = stamp; event(state, caseId, "Admin", action, "Estimate sent to the customer", "Customer approval is now required.", "customer"); }
  else if (action === "activate_project") { item.stage = "active_project"; event(state, caseId, "Admin", action, "Customer-approved work converted to an active project", item.projectCode); }
  else if (action === "submit_progress_update") { if (!payload.fileIds?.length) throw new Error("At least one progress photo is required."); const files = item.files.filter((file: any) => payload.fileIds.includes(file.id)); const update = { id: state.nextId++, caseId, workDate: payload.workDate, supervisorEmail: "site.supervisor@alerttradiepro.demo", internalUpdate: payload.internalUpdate, customerUpdate: payload.customerUpdate, status: "pending_admin", adminNote: "", ownerNote: "", createdAt: stamp, adminReviewedAt: "", ownerReviewedAt: "", publishedAt: "", files }; item.updates.unshift(update); event(state, caseId, "Site Supervisor", action, "Daily update submitted to Admin"); }
  else if (action === "admin_approve_update") { const update = item.updates.find((entry: any) => entry.id === payload.updateId); update.status = "pending_owner"; update.adminReviewedAt = stamp; event(state, caseId, "Admin", action, "Admin approved the customer update", "Owner approval is still required."); }
  else if (action === "owner_approve_update") { const update = item.updates.find((entry: any) => entry.id === payload.updateId); update.status = "published"; update.ownerReviewedAt = stamp; update.publishedAt = stamp; update.files.forEach((file: any) => { file.visibility = "published"; file.publishedAt = stamp; }); event(state, caseId, "Owner", action, "Owner approved and published the customer update", "The approved text and photos are now visible to the customer.", "customer"); }
  else if (action === "reject_update") { const update = item.updates.find((entry: any) => entry.id === payload.updateId); update.status = "changes_requested"; event(state, caseId, role === "owner" ? "Owner" : "Admin", action, "Customer update returned to Site Supervisor", payload.note); }
  else throw new Error("Unknown workflow action.");
  item.updatedAt = stamp;
}

export function installWorkflowDemoApi() {
  const previous = window.fetch.bind(window);
  window.fetch = async (input: RequestInfo | URL, init: RequestInit = {}) => {
    const raw = typeof input === "string" ? input : input instanceof URL ? input.href : input.url; const url = new URL(raw, location.href); const method = (init.method ?? "GET").toUpperCase();
    if (!url.pathname.includes("/api/workflow")) return previous(input, init);
    const state = load();
    try {
      if (url.pathname.endsWith("/api/workflow/files") && method === "POST") { const form = init.body as FormData; const caseId = Number(form.get("caseId")); const file = form.get("file") as File; const category = String(form.get("category")); const item = state.cases.find((entry) => entry.id === caseId); if (!item || !file) throw new Error("Choose a valid project photo."); const id = state.nextId++; const dataUrl = await readFile(file); const record = { id, caseId, updateId: 0, category, fileName: file.name, mimeType: file.type, sizeBytes: file.size, uploadedBy: "site.supervisor@alerttradiepro.demo", visibility: "internal", uploadedAt: new Date().toISOString(), publishedAt: "", url: dataUrl }; item.files.unshift(record); event(state, caseId, "Site Supervisor", "photo_uploaded", `${category === "site_visit" ? "Site visit" : "Progress"} photo uploaded`, file.name); save(state); return json({ data: record }, 201); }
      if (url.pathname.endsWith("/api/workflow/public")) {
        if (method === "POST") { const payload = JSON.parse(String(init.body ?? "{}")); const id = state.nextId++; const code = `REQ-2026-${String(Date.now()).slice(-6)}`; state.cases.unshift({ id, requestCode: code, projectCode: "", customerName: payload.name, customerEmail: payload.email, customerPhone: payload.phone, service: payload.service, suburb: payload.location, description: payload.details, timeframe: payload.timeframe, budget: payload.budget, stage: "request_submitted", assignedSupervisorEmail: "", assignedSupervisorName: "", siteVisitAt: "", projectFolder: "", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), visitReport: null, estimate: null, files: [], updates: [] }); event(state, id, "Customer", "request_submitted", "Customer submitted a new project request", `${payload.service} · ${payload.location}`); save(state); return json({ data: { caseId: id, code } }, 201); }
        const body = method === "PATCH" ? JSON.parse(String(init.body ?? "{}")) : {}; const code = method === "PATCH" ? body.code : url.searchParams.get("code"); const item = state.cases.find((entry) => entry.requestCode === code || entry.projectCode === code); if (!item) return json({ error: "We could not find that project reference." }, 404);
        if (method === "PATCH") { item.estimate.status = body.decision === "accept" ? "customer_accepted" : "customer_declined"; item.stage = body.decision === "accept" ? "customer_approved" : "estimate_declined"; item.estimate.customerDecidedAt = new Date().toISOString(); event(state, item.id, "Customer", "customer_estimate_decision", body.decision === "accept" ? "Customer accepted the estimate" : "Customer declined the estimate", "", "customer"); save(state); }
        return json({ data: publicData(item, state) });
      }
      const role = (url.searchParams.get("previewRole") ?? "admin") as Role;
      if (method === "GET") return json({ data: snapshot(state, role) });
      const body = JSON.parse(String(init.body ?? "{}")); perform(state, role, body.action, Number(body.caseId), body.payload ?? {}); save(state); return json({ data: snapshot(state, role) });
    } catch (error) { return json({ error: error instanceof Error ? error.message : "Workflow action failed." }, 400); }
  };
}
