const OWNER_COOKIE = "atp_owner_session";
const SESSION_SECONDS = 60 * 60 * 8;
const encoder = new TextEncoder();

function base64UrlEncode(input: Uint8Array | string) { const bytes = typeof input === "string" ? encoder.encode(input) : input; let binary = ""; for (const byte of bytes) binary += String.fromCharCode(byte); return btoa(binary).replaceAll("+", "-").replaceAll("/", "_").replaceAll("=", ""); }
function base64UrlDecode(input: string) { const padded = input.replaceAll("-", "+").replaceAll("_", "/").padEnd(Math.ceil(input.length / 4) * 4, "="); const binary = atob(padded); return Uint8Array.from(binary, (character) => character.charCodeAt(0)); }
function safeEqual(left: Uint8Array, right: Uint8Array) { if (left.length !== right.length) return false; let difference = 0; for (let index = 0; index < left.length; index += 1) difference |= left[index] ^ right[index]; return difference === 0; }
function requiredEnvironmentValue(name: "OWNER_EMAIL" | "OWNER_PASSWORD_HASH" | "OWNER_SESSION_SECRET") { const value = process.env[name]?.trim(); if (!value) throw new Error(`${name} is not configured.`); return value; }
async function hmac(value: string) { const key = await crypto.subtle.importKey("raw", encoder.encode(requiredEnvironmentValue("OWNER_SESSION_SECRET")), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); return new Uint8Array(await crypto.subtle.sign("HMAC", key, encoder.encode(value))); }
export function registeredOwnerEmail() { return requiredEnvironmentValue("OWNER_EMAIL").toLowerCase(); }
export async function verifyOwnerPassword(password: string) { const [algorithm, iterationsText, saltText, expectedText] = requiredEnvironmentValue("OWNER_PASSWORD_HASH").split("$"); const iterations = Number(iterationsText); if (algorithm !== "pbkdf2" || iterations !== 100_000 || !saltText || !expectedText) return false; const key = await crypto.subtle.importKey("raw", encoder.encode(password), "PBKDF2", false, ["deriveBits"]); const expected = base64UrlDecode(expectedText); const actual = new Uint8Array(await crypto.subtle.deriveBits({ name: "PBKDF2", hash: "SHA-256", salt: base64UrlDecode(saltText), iterations }, key, expected.length * 8)); return safeEqual(actual, expected); }
export async function createOwnerSession(email: string) { const payload = base64UrlEncode(JSON.stringify({ email: email.toLowerCase(), expires: Date.now() + SESSION_SECONDS * 1000 })); return `${payload}.${base64UrlEncode(await hmac(payload))}`; }
export async function verifyOwnerSession(token?: string | null) { if (!token) return null; const [payload, signatureText, extra] = token.split("."); if (!payload || !signatureText || extra) return null; if (!safeEqual(await hmac(payload), base64UrlDecode(signatureText))) return null; try { const parsed = JSON.parse(new TextDecoder().decode(base64UrlDecode(payload))) as { email?: string; expires?: number }; if (!parsed.email || !parsed.expires || parsed.expires < Date.now() || parsed.email.toLowerCase() !== registeredOwnerEmail()) return null; return { email: parsed.email.toLowerCase(), expires: parsed.expires }; } catch { return null; } }
export function ownerCookieName() { return OWNER_COOKIE; }
export function ownerSessionCookie(token: string, secure: boolean) { return `${OWNER_COOKIE}=${token}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${SESSION_SECONDS}${secure ? "; Secure" : ""}`; }
export function clearOwnerSessionCookie(secure: boolean) { return `${OWNER_COOKIE}=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0${secure ? "; Secure" : ""}`; }
export function cookieValue(request: Request, name: string) { const cookies = request.headers.get("cookie") ?? ""; for (const part of cookies.split(";")) { const [key, ...value] = part.trim().split("="); if (key === name) return value.join("="); } return null; }
export function requestIsSameOrigin(request: Request) { const origin = request.headers.get("origin"); return !origin || origin === new URL(request.url).origin; }
export async function ownerSessionFromRequest(request: Request) { return verifyOwnerSession(cookieValue(request, OWNER_COOKIE)); }
