import { listStaffAccessRequests, reviewStaffAccessRequest } from "./staff-store";
import { staffRoles, type StaffRole } from "../app/admin-auth";
import { runtimeBindings } from "./runtime";

type Resource = "project" | "finance" | "schedule" | "report" | "message" | "permission" | "staff";
async function database() { const env = await runtimeBindings(); if (!env.DB) throw new Error("The owner database is unavailable."); return env.DB; }
export async function ensureOwnerDatabase() { const db = await database(); await db.batch([
  db.prepare(`CREATE TABLE IF NOT EXISTS projects (id INTEGER PRIMARY KEY AUTOINCREMENT, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, service TEXT NOT NULL, stage TEXT NOT NULL, progress INTEGER NOT NULL DEFAULT 0, contract_value INTEGER NOT NULL DEFAULT 0, balance INTEGER NOT NULL DEFAULT 0, customer_name TEXT NOT NULL DEFAULT '', suburb TEXT NOT NULL DEFAULT '', start_date TEXT NOT NULL DEFAULT '', notes TEXT NOT NULL DEFAULT '', updated_at TEXT NOT NULL)`),
  db.prepare(`CREATE TABLE IF NOT EXISTS finance_entries (id INTEGER PRIMARY KEY AUTOINCREMENT, type TEXT NOT NULL, category TEXT NOT NULL, project_code TEXT NOT NULL DEFAULT 'Business / General', amount INTEGER NOT NULL, entry_date TEXT NOT NULL, note TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL)`),
  db.prepare(`CREATE TABLE IF NOT EXISTS schedule_events (id INTEGER PRIMARY KEY AUTOINCREMENT, event_date TEXT NOT NULL, start_time TEXT NOT NULL, title TEXT NOT NULL, assignee TEXT NOT NULL, project_code TEXT NOT NULL DEFAULT 'Business / General', tone TEXT NOT NULL DEFAULT 'gold', notes TEXT NOT NULL DEFAULT '')`),
  db.prepare(`CREATE TABLE IF NOT EXISTS eod_reports (id INTEGER PRIMARY KEY AUTOINCREMENT, person TEXT NOT NULL, role TEXT NOT NULL, project_code TEXT NOT NULL, summary TEXT NOT NULL, submitted_at TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'Pending', owner_note TEXT NOT NULL DEFAULT '')`),
  db.prepare(`CREATE TABLE IF NOT EXISTS team_messages (id INTEGER PRIMARY KEY AUTOINCREMENT, sender TEXT NOT NULL, recipient TEXT NOT NULL, body TEXT NOT NULL, sent_at TEXT NOT NULL)`),
  db.prepare(`CREATE TABLE IF NOT EXISTS role_permissions (role TEXT PRIMARY KEY, projects INTEGER NOT NULL DEFAULT 1, schedule INTEGER NOT NULL DEFAULT 1, finance INTEGER NOT NULL DEFAULT 0, finance_export INTEGER NOT NULL DEFAULT 0, updated_at TEXT NOT NULL)`),
  db.prepare(`CREATE TABLE IF NOT EXISTS login_attempts (key TEXT PRIMARY KEY, failed_count INTEGER NOT NULL DEFAULT 0, locked_until INTEGER NOT NULL DEFAULT 0, updated_at INTEGER NOT NULL)`),
  db.prepare(`CREATE TABLE IF NOT EXISTS job_requests (id INTEGER PRIMARY KEY AUTOINCREMENT, code TEXT NOT NULL UNIQUE, request_type TEXT NOT NULL, customer_name TEXT NOT NULL, contact TEXT NOT NULL DEFAULT '', service TEXT NOT NULL, suburb TEXT NOT NULL DEFAULT '', submitted_at TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'New', priority TEXT NOT NULL DEFAULT 'Normal', summary TEXT NOT NULL DEFAULT '', assigned_to TEXT NOT NULL DEFAULT 'Unassigned', updated_at TEXT NOT NULL)`),
  db.prepare(`CREATE TABLE IF NOT EXISTS staff_access_requests (id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'Pending', role TEXT NOT NULL DEFAULT 'Unassigned', trade_title TEXT NOT NULL DEFAULT '', requested_at TEXT NOT NULL, reviewed_at TEXT NOT NULL DEFAULT '', last_seen_at TEXT NOT NULL)`),
  db.prepare(`CREATE TABLE IF NOT EXISTS request_files (id INTEGER PRIMARY KEY AUTOINCREMENT, request_code TEXT NOT NULL, object_key TEXT NOT NULL UNIQUE, original_name TEXT NOT NULL, content_type TEXT NOT NULL, size INTEGER NOT NULL, uploaded_at TEXT NOT NULL)`),
  db.prepare(`CREATE INDEX IF NOT EXISTS request_files_code_idx ON request_files(request_code)`),
]); }
async function seedOwnerDatabase() { const db = await database(); const counts = await db.batch([db.prepare("SELECT COUNT(*) AS total FROM projects"),db.prepare("SELECT COUNT(*) AS total FROM finance_entries"),db.prepare("SELECT COUNT(*) AS total FROM schedule_events"),db.prepare("SELECT COUNT(*) AS total FROM eod_reports"),db.prepare("SELECT COUNT(*) AS total FROM team_messages")]); const total=(i:number)=>Number((counts[i].results[0] as {total?:number}|undefined)?.total??0); const statements:ReturnType<typeof db.prepare>[]=[]; const now=new Date().toISOString();
 if(!total(0)){for(const row of [["ATP-2026-00124","Glen Waverley renovation","Home Renovation","Construction",62,18400000,5520000,"Customer 124","Glen Waverley","2026-04-14","Framing and rough-in stage."],["ATP-2026-00131","Structural assessment 131","Engineering","Site inspection",28,1860000,930000,"Customer 131","Rowville","2026-08-03","Engineering inspection and report."],["ATP-2026-00136","Bathroom renovation 136","Bathroom Renovation","Estimate",18,4280000,4280000,"Customer 136","Wantirna","2026-08-12","Scope and supplier pricing in review."],["ATP-2026-00141","Home extension 141","Home Extension","Admin review",8,0,0,"Customer 141","Wheelers Hill","","New request awaiting owner review."]]) statements.push(db.prepare("INSERT INTO projects (code,name,service,stage,progress,contract_value,balance,customer_name,suburb,start_date,notes,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)").bind(...row,now)); }
 if(!total(1)){for(const row of [["Income","Progress payment","ATP-2026-00124",3680000,"2026-08-08","Deposit progress claim"],["Outcome","Plumbing","ATP-2026-00124",1240000,"2026-08-07","Rough-in invoice"],["Outcome","Materials","ATP-2026-00124",875000,"2026-08-06","Timber and fixings"],["Income","Engineering invoice","ATP-2026-00131",420000,"2026-08-05","Inspection payment"],["Income","Progress payment","ATP-2026-00124",5520000,"2026-07-15","Construction stage"],["Outcome","Labour","ATP-2026-00124",2310000,"2026-07-12","Site labour"],["Income","Progress payment","ATP-2026-00124",3680000,"2026-06-18","Demolition stage"],["Outcome","Demolition","ATP-2026-00124",1480000,"2026-06-10","Demolition contractor"]]) statements.push(db.prepare("INSERT INTO finance_entries (type,category,project_code,amount,entry_date,note,created_at) VALUES (?,?,?,?,?,?,?)").bind(...row,now)); }
 if(!total(2)){for(const row of [["2026-08-10","09:00","Owner project review","Ali Mobini","ATP-2026-00124","gold","Finance and schedule review"],["2026-08-12","07:30","Plumbing rough-in","Site Supervisor 01","ATP-2026-00124","blue","Confirm set-out before work"],["2026-08-14","10:00","Framing inspection","Site Supervisor 01","ATP-2026-00124","green","Upload inspection photos"],["2026-08-17","07:30","Electrical rough-in","Electrician","ATP-2026-00124","orange","Rebooked"],["2026-08-20","08:00","Wall lining begins","Construction team","ATP-2026-00124","blue",""]]) statements.push(db.prepare("INSERT INTO schedule_events (event_date,start_time,title,assignee,project_code,tone,notes) VALUES (?,?,?,?,?,?,?)").bind(...row)); }
 if(!total(3)){for(const row of [["Site Supervisor 01","Site Supervisor","ATP-2026-00124","Checked framing dimensions, uploaded 8 site photos and confirmed plumbing set-out.","2026-08-09T16:42:00+10:00","Pending",""],["Admin 01","Admin","ATP-2026-00136","Reviewed customer brief, prepared scope notes and requested two supplier prices.","2026-08-09T16:18:00+10:00","Pending",""],["Worker 01","Worker","ATP-2026-00124","Completed demolition clean-up and separated waste for collection.","2026-08-09T16:05:00+10:00","Approved","Good work. Keep the waste docket with the project."]]) statements.push(db.prepare("INSERT INTO eod_reports (person,role,project_code,summary,submitted_at,status,owner_note) VALUES (?,?,?,?,?,?,?)").bind(...row)); }
 if(!total(4)){for(const row of [["Site Supervisor 01","Owner","Morning Ali, the framing dimensions are checked and the plumbing set-out is ready.","2026-08-09T10:36:00+10:00"],["Owner","Site Supervisor 01","Great. Please upload the marked-up photos to Project 124 before the EOD report.","2026-08-09T10:40:00+10:00"],["Site Supervisor 01","Owner","Done — 8 photos are now attached to the project.","2026-08-09T10:44:00+10:00"]]) statements.push(db.prepare("INSERT INTO team_messages (sender,recipient,body,sent_at) VALUES (?,?,?,?)").bind(...row)); }
 statements.push(db.prepare("INSERT OR IGNORE INTO role_permissions (role,projects,schedule,finance,finance_export,updated_at) VALUES ('Admin',1,1,0,0,?)").bind(now)); if(statements.length) await db.batch(statements); }
export async function getOwnerSnapshot(){await ensureOwnerDatabase();await seedOwnerDatabase();const db=await database();const r=await db.batch([db.prepare(`SELECT id,code,name,service,stage,progress,contract_value AS contractValue,balance,customer_name AS customerName,suburb,start_date AS startDate,notes,updated_at AS updatedAt FROM projects ORDER BY updated_at DESC,id DESC`),db.prepare(`SELECT id,type,category,project_code AS projectCode,amount,entry_date AS entryDate,note,created_at AS createdAt FROM finance_entries ORDER BY entry_date DESC,id DESC`),db.prepare(`SELECT id,event_date AS eventDate,start_time AS startTime,title,assignee,project_code AS projectCode,tone,notes FROM schedule_events ORDER BY event_date,start_time`),db.prepare(`SELECT id,person,role,project_code AS projectCode,summary,submitted_at AS submittedAt,status,owner_note AS ownerNote FROM eod_reports ORDER BY submitted_at DESC,id DESC`),db.prepare(`SELECT id,sender,recipient,body,sent_at AS sentAt FROM team_messages ORDER BY sent_at,id`),db.prepare(`SELECT role,projects,schedule,finance,finance_export AS financeExport,updated_at AS updatedAt FROM role_permissions WHERE role='Admin' LIMIT 1`)]);return{projects:r[0].results,financeEntries:r[1].results,scheduleEvents:r[2].results,eodReports:r[3].results,messages:r[4].results,permissions:r[5].results[0]??{role:"Admin",projects:1,schedule:1,finance:0,financeExport:0},staffRequests:await listStaffAccessRequests()};}
function txt(v:unknown,f=""){return typeof v==="string"?v.trim():f} function num(v:unknown,f=0){const n=Number(v);return Number.isFinite(n)?n:f}
export async function createOwnerRecord(resource:Resource,p:Record<string,unknown>){await ensureOwnerDatabase();const db=await database(),now=new Date().toISOString();if(resource==="project")await db.prepare("INSERT INTO projects (code,name,service,stage,progress,contract_value,balance,customer_name,suburb,start_date,notes,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)").bind(txt(p.code).toUpperCase(),txt(p.name),txt(p.service),txt(p.stage,"Admin review"),Math.min(100,Math.max(0,num(p.progress))),Math.max(0,num(p.contractValue)),Math.max(0,num(p.balance)),txt(p.customerName),txt(p.suburb),txt(p.startDate),txt(p.notes),now).run();else if(resource==="finance")await db.prepare("INSERT INTO finance_entries (type,category,project_code,amount,entry_date,note,created_at) VALUES (?,?,?,?,?,?,?)").bind(txt(p.type),txt(p.category),txt(p.projectCode,"Business / General"),Math.max(1,num(p.amount)),txt(p.entryDate,now.slice(0,10)),txt(p.note),now).run();else if(resource==="schedule")await db.prepare("INSERT INTO schedule_events (event_date,start_time,title,assignee,project_code,tone,notes) VALUES (?,?,?,?,?,?,?)").bind(txt(p.eventDate),txt(p.startTime),txt(p.title),txt(p.assignee),txt(p.projectCode,"Business / General"),txt(p.tone,"gold"),txt(p.notes)).run();else if(resource==="message")await db.prepare("INSERT INTO team_messages (sender,recipient,body,sent_at) VALUES (?,?,?,?)").bind("Owner",txt(p.recipient,"Site Supervisor 01"),txt(p.body),now).run();else throw new Error("This record type cannot be created.");}
export async function updateOwnerRecord(resource:Resource,id:number|string,p:Record<string,unknown>){await ensureOwnerDatabase();const db=await database(),now=new Date().toISOString();if(resource==="project")await db.prepare("UPDATE projects SET code=?,name=?,service=?,stage=?,progress=?,contract_value=?,balance=?,customer_name=?,suburb=?,start_date=?,notes=?,updated_at=? WHERE id=?").bind(txt(p.code).toUpperCase(),txt(p.name),txt(p.service),txt(p.stage),Math.min(100,Math.max(0,num(p.progress))),Math.max(0,num(p.contractValue)),Math.max(0,num(p.balance)),txt(p.customerName),txt(p.suburb),txt(p.startDate),txt(p.notes),now,num(id)).run();else if(resource==="finance")await db.prepare("UPDATE finance_entries SET type=?,category=?,project_code=?,amount=?,entry_date=?,note=? WHERE id=?").bind(txt(p.type),txt(p.category),txt(p.projectCode,"Business / General"),Math.max(1,num(p.amount)),txt(p.entryDate),txt(p.note),num(id)).run();else if(resource==="schedule")await db.prepare("UPDATE schedule_events SET event_date=?,start_time=?,title=?,assignee=?,project_code=?,tone=?,notes=? WHERE id=?").bind(txt(p.eventDate),txt(p.startTime),txt(p.title),txt(p.assignee),txt(p.projectCode),txt(p.tone,"gold"),txt(p.notes),num(id)).run();else if(resource==="report")await db.prepare("UPDATE eod_reports SET status=?,owner_note=? WHERE id=?").bind(txt(p.status),txt(p.ownerNote),num(id)).run();else if(resource==="permission")await db.prepare("UPDATE role_permissions SET projects=?,schedule=?,finance=?,finance_export=?,updated_at=? WHERE role='Admin'").bind(num(p.projects)?1:0,num(p.schedule)?1:0,num(p.finance)?1:0,num(p.financeExport)?1:0,now).run();else if(resource==="staff"){const role=txt(p.role,"Unassigned");if(role!=="Unassigned"&&!staffRoles.includes(role as StaffRole))throw new Error("Select a valid staff role.");const status=txt(p.status,"Pending");if(!["Pending","Approved","Rejected"].includes(status))throw new Error("Select a valid access status.");await reviewStaffAccessRequest(num(id),status as "Pending"|"Approved"|"Rejected",role as StaffRole|"Unassigned",txt(p.tradeTitle));}else throw new Error("This record type cannot be updated.");}
export async function deleteOwnerRecord(resource:Resource,id:number){await ensureOwnerDatabase();const table=resource==="project"?"projects":resource==="finance"?"finance_entries":resource==="schedule"?"schedule_events":null;if(!table)throw new Error("This record type cannot be deleted.");const db=await database();await db.prepare(`DELETE FROM ${table} WHERE id=?`).bind(id).run();}
export async function getLoginAttempt(key:string){await ensureOwnerDatabase();const db=await database();return db.prepare("SELECT failed_count AS failedCount,locked_until AS lockedUntil FROM login_attempts WHERE key=?").bind(key).first<{failedCount:number;lockedUntil:number}>();}
export async function recordLoginFailure(key:string,failedCount:number,lockedUntil:number){await ensureOwnerDatabase();const db=await database();await db.prepare("INSERT INTO login_attempts (key,failed_count,locked_until,updated_at) VALUES (?,?,?,?) ON CONFLICT(key) DO UPDATE SET failed_count=excluded.failed_count,locked_until=excluded.locked_until,updated_at=excluded.updated_at").bind(key,failedCount,lockedUntil,Date.now()).run();}
export async function clearLoginFailures(key:string){await ensureOwnerDatabase();const db=await database();await db.prepare("DELETE FROM login_attempts WHERE key=?").bind(key).run();}
