(function(){
  'use strict';
  const script=document.currentScript,base=script?new URL('../',script.src):new URL('../',location.href),THEME_KEY='ac_product_theme_v1',ONBOARD_KEY='ac_onboarding_complete_v1';
  const css=document.createElement('style');css.textContent=`
    .ac-platform{position:fixed;left:14px;bottom:14px;z-index:90;display:flex;align-items:center;gap:6px;padding:6px;border:1px solid rgba(255,255,255,.18);border-radius:15px;background:rgba(12,12,12,.9);box-shadow:0 16px 45px rgba(0,0,0,.42);backdrop-filter:blur(14px)}.ac-platform.ac-platform-inline{position:static;margin-left:auto;box-shadow:none;background:#111;flex:none}.ac-platform button,.ac-platform a{display:flex;align-items:center;justify-content:center;gap:7px;min-width:40px;min-height:40px;padding:0 10px;border:0;border-radius:10px;background:#232323;color:#eee;text-decoration:none;font:800 11px/1.1 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;cursor:pointer}.ac-platform button:hover,.ac-platform a:hover{background:#f5b400;color:#050505}.ac-sync-dot{width:8px;height:8px;border-radius:50%;background:#888;flex:none}.ac-sync-dot.online{background:#38d281}.ac-sync-dot.syncing{background:#f5b400}.ac-sync-dot.error{background:#ff6c6c}.ac-platform-label,.ac-sync-label{max-width:180px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.ac-signout[hidden]{display:none!important}
    .ac-searchbar{display:flex;gap:9px;align-items:center;margin:0 0 16px;padding:12px;border:1px solid var(--line,#303030);border-radius:15px;background:var(--panel,#111)}.ac-searchbar input{width:100%;min-height:46px;padding:10px 12px;border:1px solid var(--line,#303030);border-radius:11px;background:var(--input,#202020);color:var(--text,#fff);font:inherit}.ac-searchbar span{color:var(--muted,#aaa);font-size:12px;font-weight:800;white-space:nowrap}
    .ac-undo{position:fixed;left:50%;bottom:22px;z-index:140;transform:translateX(-50%);display:flex;align-items:center;gap:12px;padding:11px 13px;border-radius:13px;background:#fff;color:#111;box-shadow:0 20px 60px rgba(0,0,0,.55);font:800 12px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.ac-undo button{min-height:34px;padding:0 11px;border:0;border-radius:9px;background:#f5b400;color:#050505;font-weight:900}
    .ac-onboard{position:fixed;inset:0;z-index:200;display:grid;place-items:center;padding:16px;background:rgba(0,0,0,.82);backdrop-filter:blur(12px)}.ac-onboard-card{width:min(780px,100%);padding:26px;border:1px solid #353535;border-radius:24px;background:#111;color:#f7f7f7;box-shadow:0 35px 110px rgba(0,0,0,.7)}.ac-onboard-card h2{font-size:clamp(28px,5vw,48px);letter-spacing:-.045em;margin:0}.ac-onboard-card h2 span{color:#f5b400}.ac-onboard-card>p{color:#aaa}.ac-onboard-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin:18px 0}.ac-onboard-grid div{padding:14px;border:1px solid #303030;border-radius:14px;background:#181818}.ac-onboard-grid strong,.ac-onboard-grid span{display:block}.ac-onboard-grid span{color:#aaa;font-size:11px;margin-top:5px}.ac-onboard-actions{display:flex;justify-content:flex-end;gap:9px}.ac-onboard-actions button{min-height:48px;padding:0 16px;border:0;border-radius:12px;font-weight:900}.ac-onboard-sample{background:#282828;color:#fff}.ac-onboard-start{background:#f5b400;color:#050505}
    .ac-login-gate{position:fixed;inset:0;z-index:300;display:grid;place-items:center;padding:18px;background:#050505}.ac-login-card{width:min(560px,100%);padding:32px;border:1px solid #343434;border-radius:24px;background:radial-gradient(circle at 85% 0,rgba(245,180,0,.14),transparent 42%),#111;color:#f7f7f7;box-shadow:0 35px 100px #000}.ac-login-card em{color:#f5b400;font-style:normal;font-size:11px;font-weight:950;letter-spacing:.13em;text-transform:uppercase}.ac-login-card h2{font-size:clamp(32px,6vw,52px);line-height:1;letter-spacing:-.05em;margin:10px 0}.ac-login-card p{color:#aaa;line-height:1.55}.ac-login-card a{display:grid;place-items:center;min-height:52px;margin-top:17px;border-radius:13px;background:#f5b400;color:#050505;text-decoration:none;font-weight:950}
    .ac-legal-footer{display:flex;justify-content:center;gap:14px;flex-wrap:wrap;padding:18px 90px 82px;color:var(--muted,#aaa);background:var(--bg,#050505);font:800 11px/1.4 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.ac-legal-footer a{color:inherit;text-decoration:none}.ac-legal-footer a:hover,.ac-legal-footer a:focus{color:#f5b400}.ac-legal-footer span{opacity:.62}
    html[data-ac-theme="light"]{color-scheme:light;--bg:#f3f0ea!important;--panel:#fcfbf8!important;--panel2:#ebe6de!important;--panel-2:#ebe6de!important;--input:#fff!important;--text:#202526!important;--muted:#67645f!important;--line:#d6d0c6!important;--yellow:#b58a45!important;--yellow2:#75562d!important;--shadow:0 18px 48px rgba(54,48,40,.10)!important}
    html[data-ac-theme="light"] body,html[data-ac-theme="light"] .shell{color:#202526!important;background-color:#f3f0ea!important;background-image:radial-gradient(circle at 18% 0,rgba(255,255,255,.82),transparent 34%),linear-gradient(135deg,rgba(181,138,69,.025),transparent 45%)!important;background-size:auto!important}
    html[data-ac-theme="light"] .topbar,html[data-ac-theme="light"] .top{position:relative;background:rgba(252,251,248,.96)!important;border-color:#d6d0c6!important;border-bottom:1px solid #d6d0c6!important;box-shadow:0 8px 30px rgba(54,48,40,.07)!important;color:#202526!important}
    html[data-ac-theme="light"] .brand-logo-dark{display:none!important}html[data-ac-theme="light"] .brand-logo-light{display:block!important}
    html[data-ac-theme="light"] .hero,html[data-ac-theme="light"] .panel-head{color:#202526!important;background-color:#f8f6f1!important;background-image:linear-gradient(145deg,#fdfcf9,#e9e4dc)!important;background-size:auto!important;border-color:#d6d0c6!important}
    html[data-ac-theme="light"] .hero:after{background:linear-gradient(180deg,transparent 52%,rgba(243,240,234,.82) 82%,#f3f0ea 100%)!important}
    html[data-ac-theme="light"] h1,html[data-ac-theme="light"] h2,html[data-ac-theme="light"] h3{color:#202527}
    html[data-ac-theme="light"] .eyebrow,html[data-ac-theme="light"] .tools-title,html[data-ac-theme="light"] .category-icon{color:#8c6936!important}
    html[data-ac-theme="light"] .nav a{color:#202527!important}html[data-ac-theme="light"] .nav svg{stroke:#b77e00!important}
    html[data-ac-theme="light"] .tool-filter,html[data-ac-theme="light"] .controls,html[data-ac-theme="light"] .filters,html[data-ac-theme="light"] .ac-searchbar{background:#ebe6de!important;border:1px solid #d2cbc0!important;box-shadow:inset 0 1px rgba(255,255,255,.8)!important}
    html[data-ac-theme="light"] .tool{color:#202526!important;background:#fcfbf8!important;border:1px solid #d6d0c6!important;box-shadow:0 14px 38px rgba(54,48,40,.08)!important}
    html[data-ac-theme="light"] .tool:before{background:none!important;border-color:rgba(181,138,69,.18)!important}
    html[data-ac-theme="light"] .tool:hover,html[data-ac-theme="light"] .tool:focus-visible{border-color:#b58a45!important;box-shadow:0 22px 48px rgba(54,48,40,.14)!important}
    html[data-ac-theme="light"] .tool p,html[data-ac-theme="light"] .intro p,html[data-ac-theme="light"] .subtitle,html[data-ac-theme="light"] .item-desc,html[data-ac-theme="light"] .section p,html[data-ac-theme="light"] .panel-head p,html[data-ac-theme="light"] .scope-head p,html[data-ac-theme="light"] .lead{color:#67645f!important}
    html[data-ac-theme="light"] .trust{color:#75562d!important;background:#f7f0e4!important;border-color:#cfb27f!important}
    html[data-ac-theme="light"] .go,html[data-ac-theme="light"] button:not(.secondary):not(.ghost):not(.danger):not(.text-action){background:#202526!important;color:#fff!important;box-shadow:0 8px 20px rgba(32,37,38,.14)}
    html[data-ac-theme="light"] .tool,html[data-ac-theme="light"] .section,html[data-ac-theme="light"] .panel,html[data-ac-theme="light"] .sidebar,html[data-ac-theme="light"] .detail,html[data-ac-theme="light"] .question,html[data-ac-theme="light"] .scope-block,html[data-ac-theme="light"] .record,html[data-ac-theme="light"] .task,html[data-ac-theme="light"] .total-card,html[data-ac-theme="light"] .budget-card,html[data-ac-theme="light"] .category,html[data-ac-theme="light"] .recommend,html[data-ac-theme="light"] .breakdown,html[data-ac-theme="light"] .result-box,html[data-ac-theme="light"] .estimate-card,html[data-ac-theme="light"] .confidence-card,html[data-ac-theme="light"] .evidence,html[data-ac-theme="light"] .comparable,html[data-ac-theme="light"] .file-box,html[data-ac-theme="light"] .doc-group,html[data-ac-theme="light"] .permit,html[data-ac-theme="light"] .stat,html[data-ac-theme="light"] .table,html[data-ac-theme="light"] .lock,html[data-ac-theme="light"] .notice{background:#fcfbf8!important;color:#202526!important;border-color:#d6d0c6!important;box-shadow:0 10px 28px rgba(54,48,40,.065)}
    html[data-ac-theme="light"] .step,html[data-ac-theme="light"] .choice label,html[data-ac-theme="light"] .scope-check,html[data-ac-theme="light"] .budget-stat,html[data-ac-theme="light"] .trade-title,html[data-ac-theme="light"] .cost-footer,html[data-ac-theme="light"] .custom-scopes,html[data-ac-theme="light"] .actions{background:#eee9e1!important;color:#363c3e!important;border-color:#d6d0c6!important}
    html[data-ac-theme="light"] .step b{background:#d8d2c6!important;color:#353b3d!important}html[data-ac-theme="light"] .step.active{background:#f7f0e4!important;color:#202526!important;border-color:#b58a45!important}html[data-ac-theme="light"] .step.active b,html[data-ac-theme="light"] .step.done b{background:#b58a45!important;color:#fff!important}
    html[data-ac-theme="light"] .logo{background:#b58a45!important;color:#fff!important;border:1px solid #98713a!important;box-shadow:inset 0 1px rgba(255,255,255,.4)}
    html[data-ac-theme="light"] input,html[data-ac-theme="light"] select,html[data-ac-theme="light"] textarea{background:#fff!important;color:#202527!important;border-color:#aaa396!important;box-shadow:inset 0 1px 2px rgba(45,49,50,.05)!important}
    html[data-ac-theme="light"] input:focus,html[data-ac-theme="light"] select:focus,html[data-ac-theme="light"] textarea:focus{border-color:#a47b3e!important;box-shadow:0 0 0 3px rgba(181,138,69,.16)!important}
    html[data-ac-theme="light"] label,html[data-ac-theme="light"] .field label,html[data-ac-theme="light"] .question label.title{color:#343a3c!important}
    html[data-ac-theme="light"] .btn.secondary,html[data-ac-theme="light"] button.secondary{background:#293033!important;color:#fff!important;border-color:#293033!important}html[data-ac-theme="light"] .btn.ghost,html[data-ac-theme="light"] button.ghost{color:#343a3c!important;background:transparent!important}
    html[data-ac-theme="light"] .grand-total,html[data-ac-theme="light"] .estimate-main,html[data-ac-theme="light"] .total{color:#7d5d2f!important}
    html[data-ac-theme="light"] .tip{background:#eef4f4!important;color:#344144!important;border-color:#aebfc0!important}html[data-ac-theme="light"] .tip b{color:#202527!important}
    html[data-ac-theme="light"] .missing,html[data-ac-theme="light"] .pre-disclaimer,html[data-ac-theme="light"] .disclaimer,html[data-ac-theme="light"] .final-warning{background:#fff8e4!important;color:#594c2d!important;border-color:#d1a642!important}
    html[data-ac-theme="light"] .result-banner strong,html[data-ac-theme="light"] .missing h3,html[data-ac-theme="light"] .disclaimer strong{color:#202527!important}
    html[data-ac-theme="light"] .ac-platform{background:rgba(252,251,248,.97)!important;border-color:#d1cabf!important;box-shadow:0 10px 28px rgba(54,48,40,.12)!important}html[data-ac-theme="light"] .ac-platform.ac-platform-inline{background:#eee9e1!important}
    html[data-ac-theme="light"] .ac-platform button,html[data-ac-theme="light"] .ac-platform a{background:#fcfbf8!important;color:#202526!important;border:1px solid #d6d0c6!important}html[data-ac-theme="light"] .ac-platform button:hover,html[data-ac-theme="light"] .ac-platform a:hover{background:#202526!important;color:#fff!important}
    html[data-ac-theme="light"] .ac-legal-footer,html[data-ac-theme="light"] .footer{background:#e9e4dc!important;color:#5f5c57!important;border-color:#d2cbc0!important}
    html[data-ac-theme="light"] .ac-onboard-card,html[data-ac-theme="light"] .ac-login-card{background:#fffefb!important;color:#202527!important;border-color:#bdb6a8!important;box-shadow:0 30px 80px rgba(43,47,48,.22)!important}html[data-ac-theme="light"] .ac-onboard-grid div{background:#ebe7dd!important;border-color:#c9c3b6!important}
    @media(max-width:980px){.ac-platform.ac-platform-inline .ac-sync-label,.ac-platform.ac-platform-inline .ac-platform-label,.ac-platform.ac-platform-inline .ac-signout{display:none!important}}@media(max-width:680px){.ac-platform{left:8px;bottom:8px}.ac-platform:not(.ac-platform-inline) .ac-platform-label,.ac-platform:not(.ac-platform-inline) .ac-sync-label{display:none}.ac-onboard-grid{grid-template-columns:1fr}.ac-onboard-actions{display:grid;grid-template-columns:1fr}.ac-onboard-actions button{width:100%}.ac-legal-footer{padding:18px 72px 78px 12px;justify-content:flex-start}}
    @media print{.ac-platform,.ac-searchbar,.ac-onboard,.ac-undo,.ac-legal-footer{display:none!important}}
  `;document.head.appendChild(css);
  function applyTheme(value){document.documentElement.dataset.acTheme=value;localStorage.setItem(THEME_KEY,value);const button=document.querySelector('[data-ac-theme-toggle]');if(button)button.textContent=value==='light'?'☀ Daylight':'☾ Dark'}
  applyTheme(localStorage.getItem(THEME_KEY)||'dark');
  const tools=document.createElement('div'),dashboardHeader=document.querySelector('.topbar');tools.className='ac-platform'+(dashboardHeader?' ac-platform-inline':'');tools.innerHTML='<button type="button" data-ac-theme-toggle title="Switch daylight mode">☾ Dark</button><button type="button" data-ac-sync title="Project sync status"><i class="ac-sync-dot"></i><span class="ac-sync-label">Local only</span></button><a data-ac-account href="'+new URL('login/',base).href+'"><span class="ac-platform-label">Sign in</span></a><button class="ac-signout" type="button" hidden>Sign out</button>';(dashboardHeader||document.body).appendChild(tools);applyTheme(localStorage.getItem(THEME_KEY)||'dark');
  tools.querySelector('[data-ac-theme-toggle]').addEventListener('click',()=>applyTheme(document.documentElement.dataset.acTheme==='light'?'dark':'light'));
  function updateAccount(){const label=tools.querySelector('.ac-platform-label'),user=window.ACAuth?.user(),profile=window.ACAuth?.profile(),active=window.ACAuth?.hasAccess?.();label.textContent=user?(active?`${user.email||'Account'} • ${String(profile?.role||'team').replace('_',' ')}`:`${user.email||'Account'} • access inactive`):'Sign in';tools.querySelector('[data-ac-account]').title=user?'Account, team and recent activity':'Sign in';tools.querySelector('.ac-signout').hidden=!user}
  window.addEventListener('ac-auth-ready',updateAccount);window.addEventListener('ac-auth-changed',updateAccount);updateAccount();
  tools.querySelector('.ac-signout').addEventListener('click',async()=>{if(!confirm('Sign out of Alert Construction on this device?'))return;await window.ACAuth?.signOut();location.href=new URL('',base).href});
  function syncState(value,message){const dot=tools.querySelector('.ac-sync-dot'),label=tools.querySelector('.ac-sync-label'),button=tools.querySelector('[data-ac-sync]');dot.className='ac-sync-dot '+(value||'');const fallback={online:'Synced now',syncing:'Syncing…',error:'Sync unavailable'}[value]||'Local only';label.textContent=message||fallback;button.title=message||{online:'Projects synced',syncing:'Syncing projects',error:'Sync unavailable'}[value]||'Projects saved locally'}
  window.addEventListener('ac-cloud-status',event=>syncState(event.detail?.status,event.detail?.message));syncState(navigator.onLine?'':'error');window.addEventListener('offline',()=>syncState('error','Offline • saved locally'));
  function addSearch(){if(document.getElementById('search')||document.querySelector('.ac-searchbar'))return;const items=[...document.querySelectorAll('.item')];if(items.length<5)return;const host=document.querySelector('#itemsWrap,.sections');if(!host)return;const bar=document.createElement('div');bar.className='ac-searchbar';bar.innerHTML='<span>Search items</span><input type="search" placeholder="Type an item name, category or description…" aria-label="Search estimate items">';host.parentNode.insertBefore(bar,host);bar.querySelector('input').addEventListener('input',event=>{const q=event.target.value.toLowerCase().trim();items.forEach(item=>item.hidden=!!q&&!item.textContent.toLowerCase().includes(q))})}
  function protectClear(){const clear=document.getElementById('clearBtn');if(!clear||clear.dataset.acProtected)return;clear.dataset.acProtected='1';clear.addEventListener('click',event=>{const inputs=[...document.querySelectorAll('.qtyInput')],snapshot=inputs.map(input=>input.value);if(!snapshot.some(value=>Number(value)>0))return;if(!confirm('Clear all quantities? You can undo immediately afterwards.')){event.preventDefault();event.stopImmediatePropagation();return}setTimeout(()=>showUndo(inputs,snapshot),20)},true)}
  function showUndo(inputs,snapshot){document.querySelector('.ac-undo')?.remove();const bar=document.createElement('div');bar.className='ac-undo';bar.innerHTML='<span>Quantities cleared</span><button type="button">Undo</button>';document.body.appendChild(bar);const timer=setTimeout(()=>bar.remove(),7000);bar.querySelector('button').addEventListener('click',()=>{clearTimeout(timer);inputs.forEach((input,index)=>{input.value=snapshot[index];input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}))});bar.remove()})}
  function onboarding(){const path=location.pathname.replace(/index\.html$/,'').replace(/\/+$/,'/');if(localStorage.getItem(ONBOARD_KEY)||!/\/$/.test(path)||!document.querySelector('.tools-grid'))return;const modal=document.createElement('div');modal.className='ac-onboard';modal.innerHTML='<div class="ac-onboard-card"><h2>Welcome to your <span>Building Clinic.</span></h2><p>Quotes, projects, site work and follow-ups now live in one connected workspace.</p><div class="ac-onboard-grid"><div><strong>1. Create a project</strong><span>Keep every estimate, quote review and task together.</span></div><div><strong>2. Build the estimate</strong><span>Use a trade calculator, plan review or renovation planner.</span></div><div><strong>3. Save and continue</strong><span>Open the same record later from Projects.</span></div></div><div class="ac-onboard-actions"><button class="ac-onboard-sample" type="button">Create Sample Project</button><button class="ac-onboard-start" type="button">Explore the App</button></div></div>';document.body.appendChild(modal);const close=()=>{localStorage.setItem(ONBOARD_KEY,'1');modal.remove()};modal.querySelector('.ac-onboard-start').addEventListener('click',close);modal.querySelector('.ac-onboard-sample').addEventListener('click',()=>{if(window.ACProjects){const project=ACProjects.create({name:'Sample Renovation Project',address:'Example site',client:'Sample Client',status:'Quoting',notes:'A safe sample project. Delete it whenever you are ready.'});ACProjects.addTask(project.id,{title:'Review bathroom estimate',dueDate:ACProjects.today(),priority:'High'});ACProjects.addRecord(project.id,{module:'general',title:'Welcome to Projects',summary:'Estimates, quote reviews, site visits and tasks will appear here.',data:{sample:true}})}close();location.href=new URL('projects/',base).href})}
  function registerOffline(){if(!('serviceWorker'in navigator)||!/^https?:$/.test(location.protocol))return;window.addEventListener('load',()=>navigator.serviceWorker.register(new URL('sw.js',base)).catch(()=>{}))}
  function addLegalFooter(){if(document.querySelector('.ac-legal-footer'))return;const footer=document.createElement('footer');footer.className='ac-legal-footer';footer.setAttribute('aria-label','Legal information');footer.innerHTML='<a href="'+new URL('legal/privacy.html',base).href+'">Privacy Policy</a><span>•</span><a href="'+new URL('legal/terms.html',base).href+'">Terms of Use</a><span>•</span><span>Estimates only • Human verification required</span>';document.body.appendChild(footer)}
  function loadAnalytics(){if(window.ACAnalytics||document.querySelector('script[data-ac-analytics]'))return;const analytics=document.createElement('script');analytics.src=new URL('shared/analytics.js',base).href;analytics.dataset.acAnalytics='1';analytics.defer=true;document.head.appendChild(analytics)}
  async function loginGate(){const config=window.AC_PLATFORM_CONFIG||{},protectedPath=/\/(electrical|plumbing|cladding|renovation-budget|property-estimate|permit-checklist|plan-ai|quote-analysis|projects|checklist|catalogue)\//.test(location.pathname);if(!config.enforceInternalLogin||!protectedPath||!window.ACAuth)return;await window.ACAuth.ready;if(window.ACAuth.hasAccess?.())return;const signedIn=window.ACAuth.isSignedIn(),profile=window.ACAuth.profile?.(),gate=document.createElement('div');gate.className='ac-login-gate';gate.innerHTML='<div class="ac-login-card"><em>Secure workspace setup</em><h2>'+(signedIn?'Continue individually or join a team.':'Sign in to continue.')+'</h2><p>'+(signedIn?(profile?.active===false?'Your previous team access is inactive, but you can create your own private workspace and use the app individually without a Team Code.':'Finish your free individual workspace setup—no Team Code is required. You can also enter one if an existing team invited you.'):'Create your own private workspace or optionally join an existing team. A Team Code is never required for individual use.')+'</p><a href="'+new URL('login/?next='+encodeURIComponent(location.pathname+location.search),base).href+'">'+(signedIn?'Choose Individual or Team':'Open Secure Account')+'</a></div>';document.body.appendChild(gate)}
  const run=()=>{addSearch();protectClear();onboarding();registerOffline();addLegalFooter();loadAnalytics();loginGate()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();
})();
