(function(global){
  'use strict';
  const config=global.AC_PLATFORM_CONFIG||{},base=String(config.supabaseUrl||'').replace(/\/$/,''),MAX_FILE=10*1024*1024;
  let members=[],selected='',pollTimer=null;
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const role=value=>({owner:'Owner',estimator:'Estimator',manager:'Project Manager',site_supervisor:'Site Supervisor'})[value]||String(value||'Team member').replace(/_/g,' ');
  async function headers(content=true){return{apikey:config.publishableKey||'',...(content?{'Content-Type':'application/json'}:{}),...await global.ACAuth.headers()}}
  async function request(path,options={}){const response=await fetch(base+path,{...options,headers:{...await headers(options.body!==undefined&&!options.raw),...(options.headers||{})}}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||data.error||`Team chat error (${response.status}).`);return data}
  async function listMembers(){const profile=global.ACAuth.profile();if(!profile?.organisation_id)return[];members=await request(`/rest/v1/profiles?organisation_id=eq.${encodeURIComponent(profile.organisation_id)}&active=eq.true&select=id,email,full_name,role&order=full_name.asc`);return members}
  function queryForConversation(){const me=global.ACAuth.user()?.id;if(!selected)return'recipient_id=is.null';return`or=(and(sender_id.eq.${me},recipient_id.eq.${selected}),and(sender_id.eq.${selected},recipient_id.eq.${me}))`}
  async function listMessages(){return request(`/rest/v1/ac_team_messages?${queryForConversation()}&deleted_at=is.null&select=id,sender_id,recipient_id,body,attachment_name,attachment_path,attachment_type,attachment_size,created_at&order=created_at.asc&limit=80`)}
  async function uploadFile(file){if(!file)return null;if(file.size>MAX_FILE)throw new Error('Attachments must be 10 MB or smaller.');const profile=global.ACAuth.profile(),user=global.ACAuth.user(),clean=file.name.replace(/[^a-zA-Z0-9._-]/g,'_').slice(-100),path=`${profile.organisation_id}/${user.id}/${crypto.randomUUID()}-${clean}`;const response=await fetch(`${base}/storage/v1/object/ac-team-chat/${path}`,{method:'POST',headers:{apikey:config.publishableKey||'',Authorization:(await global.ACAuth.headers()).Authorization,'Content-Type':file.type||'application/octet-stream','x-upsert':'false'},body:file}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||data.error||'The attachment could not be uploaded.');return{path,name:file.name.slice(0,180),type:(file.type||'application/octet-stream').slice(0,120),size:file.size}}
  async function send(body,file,recipientId=selected){const text=String(body||'').trim();if(!text&&!file)throw new Error('Write a message or attach a file.');const attachment=await uploadFile(file),profile=global.ACAuth.profile(),user=global.ACAuth.user();return request('/rest/v1/ac_team_messages',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({organisation_id:profile.organisation_id,sender_id:user.id,recipient_id:recipientId||null,body:text.slice(0,2000),attachment_path:attachment?.path||null,attachment_name:attachment?.name||null,attachment_type:attachment?.type||null,attachment_size:attachment?.size||null})})}
  async function signedAttachment(path){const data=await request(`/storage/v1/object/sign/ac-team-chat/${path}`,{method:'POST',body:JSON.stringify({expiresIn:3600})});return data.signedURL?.startsWith('http')?data.signedURL:base+String(data.signedURL||'')}
  async function unread(){const user=global.ACAuth.user();if(!user)return 0;const rows=await request(`/rest/v1/ac_team_messages?recipient_id=eq.${encodeURIComponent(user.id)}&read_at=is.null&deleted_at=is.null&select=id`);return rows.length}
  async function markRead(){if(!selected)return;await request('/rest/v1/rpc/mark_ac_team_messages_read',{method:'POST',body:JSON.stringify({p_sender:selected})}).catch(()=>{})}
  function memberName(id){const item=members.find(member=>member.id===id);return item?.full_name||item?.email||'Team member'}

  const css=document.createElement('style');css.textContent=`
    .ac-chat-launch{position:fixed;right:16px;bottom:16px;z-index:150;width:52px;height:52px;border:1px solid rgba(245,180,0,.55);border-radius:16px;background:#f5b400;color:#090909;box-shadow:0 18px 45px rgba(0,0,0,.48);font:950 20px sans-serif;cursor:pointer}.ac-chat-launch b{position:absolute;right:-5px;top:-6px;display:none;min-width:20px;height:20px;padding:0 5px;border:2px solid #0a0a0a;border-radius:999px;background:#ff6969;color:#fff;font:900 9px/16px sans-serif}.ac-chat-launch b.show{display:block}
    .ac-chat-drawer{position:fixed;right:16px;bottom:78px;z-index:151;display:none;width:min(390px,calc(100vw - 24px));height:min(620px,calc(100vh - 105px));overflow:hidden;border:1px solid #363636;border-radius:21px;background:#0e0e0e;color:#f6f6f6;box-shadow:0 28px 90px rgba(0,0,0,.72);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.ac-chat-drawer.open{display:grid;grid-template-rows:auto auto 1fr auto}.ac-chat-head{display:flex;align-items:center;justify-content:space-between;padding:16px 17px;border-bottom:1px solid #292929;background:linear-gradient(120deg,#171717,#0b0b0b)}.ac-chat-head small,.ac-chat-head strong{display:block}.ac-chat-head small{color:#f5b400;font-size:9px;font-weight:950;letter-spacing:.13em;text-transform:uppercase}.ac-chat-head strong{font-size:16px}.ac-chat-close{width:34px;height:34px;border:1px solid #333;border-radius:10px;background:#1c1c1c;color:#fff;font-size:17px}.ac-chat-target{margin:10px 12px 0;padding:10px 11px;border:1px solid #303030;border-radius:11px;background:#181818;color:#fff}.ac-chat-list{display:grid;align-content:start;gap:9px;overflow:auto;padding:13px}.ac-chat-empty{padding:30px 15px;color:#888;text-align:center;font-size:12px}.ac-chat-message{max-width:86%;padding:9px 11px;border:1px solid #2f2f2f;border-radius:13px;background:#191919}.ac-chat-message.mine{justify-self:end;border-color:rgba(245,180,0,.5);background:rgba(245,180,0,.1)}.ac-chat-message strong,.ac-chat-message span,.ac-chat-message time{display:block}.ac-chat-message strong{margin-bottom:3px;font-size:10px;color:#f5b400}.ac-chat-message span{white-space:pre-wrap;font-size:12px;line-height:1.45}.ac-chat-message time{margin-top:5px;color:#777;font-size:9px}.ac-chat-file{margin-top:7px;border:0;background:transparent;color:#9ecbff;padding:0;font-size:11px;text-align:left;cursor:pointer}.ac-chat-form{display:grid;grid-template-columns:1fr auto;gap:8px;padding:11px;border-top:1px solid #292929;background:#121212}.ac-chat-form textarea{grid-column:1/-1;width:100%;min-height:62px;max-height:110px;resize:vertical;padding:10px;border:1px solid #343434;border-radius:11px;background:#1b1b1b;color:#fff}.ac-chat-form label,.ac-chat-form button{display:grid;place-items:center;min-height:39px;border-radius:10px;font-size:11px;font-weight:900}.ac-chat-form label{border:1px solid #333;background:#222;color:#ddd;cursor:pointer}.ac-chat-form label input{display:none}.ac-chat-form button{border:0;background:#f5b400;color:#080808;padding:0 17px}.ac-chat-file-name{grid-column:1/-1;color:#999;font-size:10px}.ac-chat-error{grid-column:1/-1;color:#ff9999;font-size:10px}
    @media(max-width:620px){.ac-chat-launch{right:9px;bottom:9px}.ac-chat-drawer{right:6px;bottom:70px;width:calc(100vw - 12px);height:calc(100vh - 82px);border-radius:18px}}
  `;document.head.appendChild(css);
  const launch=document.createElement('button');launch.className='ac-chat-launch';launch.type='button';launch.title='Open team chat';launch.innerHTML='✦<b></b>';
  const drawer=document.createElement('section');drawer.className='ac-chat-drawer';drawer.setAttribute('aria-label','Team chat');drawer.innerHTML='<header class="ac-chat-head"><div><small>Team communication</small><strong>Site & office chat</strong></div><button class="ac-chat-close" type="button" aria-label="Close chat">×</button></header><select class="ac-chat-target" aria-label="Choose a team conversation"><option value="">Entire team</option></select><div class="ac-chat-list"><div class="ac-chat-empty">Open a conversation to load messages.</div></div><form class="ac-chat-form"><textarea maxlength="2000" placeholder="Message the team…" aria-label="Message"></textarea><label>Attach<input type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.doc,.docx,.xls,.xlsx,.csv,.txt"></label><button type="submit">Send</button><span class="ac-chat-file-name"></span><span class="ac-chat-error"></span></form>';
  document.body.append(launch,drawer);
  const target=drawer.querySelector('.ac-chat-target'),list=drawer.querySelector('.ac-chat-list'),form=drawer.querySelector('form'),fileInput=form.querySelector('input[type=file]'),fileName=form.querySelector('.ac-chat-file-name'),error=form.querySelector('.ac-chat-error');
  async function refresh(){try{const rows=await listMessages();list.innerHTML=rows.length?rows.map(item=>`<article class="ac-chat-message ${item.sender_id===global.ACAuth.user()?.id?'mine':''}"><strong>${esc(memberName(item.sender_id))}</strong>${item.body?`<span>${esc(item.body)}</span>`:''}${item.attachment_path?`<button class="ac-chat-file" type="button" data-path="${esc(item.attachment_path)}">📎 ${esc(item.attachment_name||'Attachment')}</button>`:''}<time>${new Date(item.created_at).toLocaleString('en-AU',{dateStyle:'medium',timeStyle:'short'})}</time></article>`).join(''):'<div class="ac-chat-empty">No messages here yet. Start the conversation.</div>';list.scrollTop=list.scrollHeight;await markRead();updateUnread()}catch(err){list.innerHTML=`<div class="ac-chat-empty">${esc(err.message)}</div>`}}
  async function updateUnread(){try{const count=await unread(),badge=launch.querySelector('b');badge.textContent=String(count);badge.classList.toggle('show',count>0)}catch(_){}}
  launch.addEventListener('click',async()=>{drawer.classList.toggle('open');if(drawer.classList.contains('open')){if(!members.length){await listMembers();const me=global.ACAuth.user()?.id;target.innerHTML='<option value="">Entire team</option>'+members.filter(member=>member.id!==me).map(member=>`<option value="${esc(member.id)}">${esc(member.full_name||member.email)} — ${esc(role(member.role))}</option>`).join('')}refresh();clearInterval(pollTimer);pollTimer=setInterval(refresh,20000)}else{clearInterval(pollTimer);pollTimer=null}});
  drawer.querySelector('.ac-chat-close').addEventListener('click',()=>{drawer.classList.remove('open');clearInterval(pollTimer);pollTimer=null});
  target.addEventListener('change',()=>{selected=target.value;form.querySelector('textarea').placeholder=selected?`Message ${memberName(selected)}…`:'Message the entire team…';refresh()});
  fileInput.addEventListener('change',()=>fileName.textContent=fileInput.files?.[0]?`Ready: ${fileInput.files[0].name}`:'');
  list.addEventListener('click',async event=>{const button=event.target.closest('[data-path]');if(!button)return;button.disabled=true;try{global.open(await signedAttachment(button.dataset.path),'_blank','noopener')}catch(err){error.textContent=err.message}finally{button.disabled=false}});
  form.addEventListener('submit',async event=>{event.preventDefault();const text=form.querySelector('textarea'),button=form.querySelector('button[type=submit]');error.textContent='';button.disabled=true;button.textContent='Sending…';try{await send(text.value,fileInput.files?.[0]||null);text.value='';fileInput.value='';fileName.textContent='';await refresh()}catch(err){error.textContent=err.message}finally{button.disabled=false;button.textContent='Send'}});
  global.ACTeamChat={listMembers,listMessages,send,signedAttachment};
  global.ACAuth.ready.then(()=>{if(global.ACAuth.hasAccess())updateUnread();else{launch.remove();drawer.remove()}});
})(window);
