(function(){
  'use strict';
  const $=id=>document.getElementById(id),config=window.AC_PLATFORM_CONFIG||{},apiBase=String(config.supabaseUrl||'').replace(/\/$/,''),preview=new URLSearchParams(location.search).get('preview')==='1',MAX_FILE=10*1024*1024;
  let state={organisation:null,members:[],sessions:[],events:[],messages:[],selectedMember:'',selectedChat:'',messageRows:[]};
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const initials=value=>String(value||'AC').split(/[\s@._-]+/).filter(Boolean).slice(0,2).map(part=>part[0]?.toUpperCase()).join('')||'AC';
  const roleLabel=value=>({owner:'Owner / Admin',estimator:'Estimator',manager:'Project Manager',site_supervisor:'Site Supervisor',pending:'Pending approval',rejected:'Declined'})[value]||String(value||'Team member').replace(/_/g,' ');
  const dateTime=value=>value?new Date(value).toLocaleString('en-AU',{dateStyle:'medium',timeStyle:'short'}):'—';
  const timeAgo=value=>{if(!value)return'No activity';const minutes=Math.max(0,Math.round((Date.now()-new Date(value).getTime())/60000));if(minutes<2)return'Active now';if(minutes<60)return`${minutes} min ago`;const hours=Math.round(minutes/60);if(hours<24)return`${hours} hr ago`;return`${Math.round(hours/24)} d ago`};
  const memberName=id=>{const member=state.members.find(item=>item.id===id);return member?.full_name||member?.email||'Team member'};
  const currentUser=()=>preview?{id:'owner-preview',email:'mamobiniali@gmail.com'}:window.ACAuth.user();
  const currentProfile=()=>preview?{id:'owner-preview',organisation_id:'org-preview',role:'owner',active:true}:window.ACAuth.profile();
  const cleanDetail=value=>String(value||'').replace(/_/g,' ').replace(/\s+/g,' ').trim();
  async function apiHeaders(content=true){return{apikey:config.publishableKey||'',...(content?{'Content-Type':'application/json'}:{}),...await ACAuth.headers()}}
  async function request(path,options={}){const response=await fetch(apiBase+path,{...options,headers:{...await apiHeaders(options.body!==undefined&&!options.raw),...(options.headers||{})}}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||data.error||`Builder Control request failed (${response.status}).`);return data}
  async function rpc(name,body={}){return request(`/rest/v1/rpc/${name}`,{method:'POST',body:JSON.stringify(body)})}

  function previewData(){
    const now=Date.now(),iso=offset=>new Date(now-offset).toISOString();
    const members=[
      {id:'owner-preview',email:'mamobiniali@gmail.com',full_name:'Ali Mobini',role:'owner',active:true,created_at:iso(90*86400000),updated_at:iso(120000)},
      {id:'mohammad-preview',email:'mohammad@alertconstruction.com.au',full_name:'Mohammad Rahimi',role:'estimator',active:true,created_at:iso(20*86400000),updated_at:iso(240000)},
      {id:'sarah-preview',email:'sarah@alertconstruction.com.au',full_name:'Sarah Chen',role:'manager',active:true,created_at:iso(35*86400000),updated_at:iso(780000)},
      {id:'liam-preview',email:'liam@alertconstruction.com.au',full_name:'Liam Walsh',role:'site_supervisor',active:true,created_at:iso(42*86400000),updated_at:iso(3700000)},
      {id:'pending-preview',email:'reza.builder@example.com',full_name:'Reza Karimi',role:'pending',active:false,created_at:iso(1500000),updated_at:iso(1500000)}
    ];
    const sessions=[
      {session_id:'s1',user_id:'owner-preview',started_at:iso(11800000),last_seen_at:iso(120000),ended_at:null,device_label:'Mac',current_path:'/builder/'},
      {session_id:'s2',user_id:'mohammad-preview',started_at:iso(9800000),last_seen_at:iso(240000),ended_at:null,device_label:'iPhone',current_path:'/quote-analysis/'},
      {session_id:'s3',user_id:'sarah-preview',started_at:iso(8700000),last_seen_at:iso(780000),ended_at:null,device_label:'Windows',current_path:'/projects/'},
      {session_id:'s4',user_id:'liam-preview',started_at:iso(14200000),last_seen_at:iso(3700000),ended_at:iso(3600000),device_label:'iPad',current_path:'/checklist/'}
    ];
    const events=[
      {id:'e1',actor_id:'mohammad-preview',action:'quote_analysis_saved',module:'quote-analysis',details:{title:'Electrical quote — Rowville'},created_at:iso(220000)},
      {id:'e2',actor_id:'sarah-preview',action:'project_record_updated',module:'projects',details:{title:'Updated master schedule',project:'Rowville Renovation'},created_at:iso(660000)},
      {id:'e3',actor_id:'liam-preview',action:'checklist_item_checked',module:'site-checklist',details:{label:'Waterproofing inspection complete'},created_at:iso(3600000)},
      {id:'e4',actor_id:'mohammad-preview',action:'tool_opened',module:'plan-ai',details:{title:'Opened AI Plan Estimator'},created_at:iso(5900000)},
      {id:'e5',actor_id:'sarah-preview',action:'file_shared',module:'team-chat',details:{title:'Shared Updated_program.pdf'},created_at:iso(7300000)},
      {id:'e6',actor_id:'owner-preview',action:'member_role_changed',module:'accounts',details:{member_id:'mohammad-preview',from:'pending',to:'estimator'},created_at:iso(86400000)},
      {id:'e7',actor_id:'mohammad-preview',action:'session_signed_in',module:'accounts',details:{device:'iPhone'},created_at:iso(9800000)}
    ];
    const messages=[
      {id:'m1',sender_id:'owner-preview',recipient_id:null,body:'Morning team — please update your project notes before 4 pm.',created_at:iso(7200000)},
      {id:'m2',sender_id:'sarah-preview',recipient_id:null,body:'Rowville schedule is updated. I moved the waterproofing check to Thursday.',attachment_name:'Updated_program.pdf',attachment_path:'preview/file',created_at:iso(6900000)},
      {id:'m3',sender_id:'owner-preview',recipient_id:'mohammad-preview',body:'Mohammad, please follow up the electrical quote and flag any item over our catalogue rate.',created_at:iso(3200000)},
      {id:'m4',sender_id:'mohammad-preview',recipient_id:'owner-preview',body:'Done — I saved the analysis and marked two items for review.',attachment_name:'Electrical_quote_review.pdf',attachment_path:'preview/file2',created_at:iso(1800000)}
    ];
    return{organisation:{id:'org-preview',name:'Alert Construction',join_code:'AC-7K9M2P',join_code_rotated_at:iso(8*86400000)},members,sessions,events,messages};
  }
  async function loadProduction(){
    await ACAuth.ready;const profile=ACAuth.profile();if(!ACAuth.hasAccess()||profile?.role!=='owner')throw new Error('Builder Control Centre is available only to the active workspace Owner.');
    const org=encodeURIComponent(profile.organisation_id),headers=await apiHeaders(),[organisations,members,sessions,events,messages,usage]=await Promise.all([
      fetch(`${apiBase}/rest/v1/organisations?id=eq.${org}&select=id,name,join_code,join_code_rotated_at`,{headers}).then(r=>r.ok?r.json():[]),
      fetch(`${apiBase}/rest/v1/profiles?organisation_id=eq.${org}&select=id,email,full_name,role,active,created_at,updated_at&order=created_at`,{headers}).then(r=>r.ok?r.json():[]),
      fetch(`${apiBase}/rest/v1/ac_staff_sessions?organisation_id=eq.${org}&select=session_id,user_id,started_at,last_seen_at,ended_at,end_reason,device_label,current_path&order=last_seen_at.desc&limit=250`,{headers}).then(r=>r.ok?r.json():[]),
      fetch(`${apiBase}/rest/v1/ac_audit_log?organisation_id=eq.${org}&select=id,actor_id,action,module,details,project_id,record_id,created_at&order=created_at.desc&limit=500`,{headers}).then(r=>r.ok?r.json():[]),
      fetch(`${apiBase}/rest/v1/ac_team_messages?organisation_id=eq.${org}&deleted_at=is.null&select=id,sender_id,recipient_id,body,attachment_name,attachment_path,attachment_type,attachment_size,read_at,created_at&order=created_at.asc&limit=500`,{headers}).then(r=>r.ok?r.json():[]),
      fetch(`${apiBase}/rest/v1/ac_usage_events?organisation_id=eq.${org}&event_name=eq.tool_opened&select=id,user_id,tool,path,occurred_at&order=occurred_at.desc&limit=250`,{headers}).then(r=>r.ok?r.json():[])
    ]);
    return{organisation:organisations[0]||null,members,sessions,events:[...events,...usage.map(item=>({id:`usage-${item.id}`,actor_id:item.user_id,action:'tool_opened',module:item.tool,details:{title:`Opened ${cleanDetail(item.tool)}`},created_at:item.occurred_at}))],messages};
  }
  async function load(){
    try{state={...state,...(preview?previewData():await loadProduction())};renderAll()}catch(error){document.querySelector('.main').innerHTML=`<section class="panel"><div class="panel-body empty"><strong>${esc(error.message)}</strong><br><br><a class="btn primary" href="../login/index.html">Open secure account</a></div></section>`}
  }
  function latestSession(userId){return state.sessions.filter(item=>item.user_id===userId).sort((a,b)=>String(b.last_seen_at).localeCompare(String(a.last_seen_at)))[0]||null}
  function online(session){return!!session&&!session.ended_at&&Date.now()-new Date(session.last_seen_at).getTime()<10*60000}
  function todayMinutes(userId){const start=new Date();start.setHours(0,0,0,0);return Math.round(state.sessions.filter(item=>item.user_id===userId&&new Date(item.last_seen_at)>=start).reduce((sum,item)=>sum+Math.max(0,new Date(item.ended_at||item.last_seen_at)-new Date(item.started_at)),0)/60000)}
  function pending(){return state.members.filter(item=>item.role==='pending'&&item.active===false)}
  function activeMembers(){return state.members.filter(item=>item.active!==false&&!['pending','rejected'].includes(item.role))}
  function latestEvents(){return[...state.events].sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at)))}
  function eventInfo(event){
    const map={session_signed_in:['↗','Signed in','good'],session_signed_out:['↙','Signed out',''],project_record_created:['＋','Created a project record','good'],project_record_updated:['↻','Updated a project record','warn'],project_record_deleted:['−','Deleted a project record',''],project_deleted:['−','Deleted a project',''],workspace_synced:['↻','Synced project workspace','good'],checklist_item_checked:['✓','Checked a site item','good'],checklist_item_unchecked:['○','Unchecked a site item','warn'],member_join_requested:['＋','Requested team access','warn'],member_join_approved:['✓','Approved a team member','good'],member_join_rejected:['×','Declined a team request',''],member_role_changed:['⇄','Changed a team role','warn'],member_access_revoked:['×','Revoked team access',''],member_access_restored:['✓','Restored team access','good'],team_code_rotated:['↻','Rotated Team Code','warn'],message_sent:['✦','Sent a team message','good'],file_shared:['▣','Shared a file','good'],tool_opened:['↗','Opened a tool',''],quote_analysis_saved:['✓','Saved a quote analysis','good']};
    const [icon,title,tone]=map[event.action]||['•',cleanDetail(event.action)||'Activity',''];const detail=event.details?.title||event.details?.label||event.details?.project||cleanDetail(event.module)||'Workspace activity';return{icon,title,tone,detail};
  }
  function renderStats(){const today=new Date();today.setHours(0,0,0,0);$('activeCount').textContent=activeMembers().length;$('onlineCount').textContent=`${activeMembers().filter(member=>online(latestSession(member.id))).length} online now`;$('pendingCount').textContent=pending().length;$('actionCount').textContent=state.events.filter(event=>new Date(event.created_at)>=today).length;$('conversationCount').textContent=1+Math.max(0,activeMembers().length-1);['overviewBadge','teamBadge'].forEach(id=>{const badge=$(id);badge.textContent=pending().length;badge.classList.toggle('show',pending().length>0)});const unread=state.messages.filter(message=>message.recipient_id===currentUser()?.id&&!message.read_at).length;$('messageBadge').textContent=unread;$('messageBadge').classList.toggle('show',unread>0)}
  function requestCard(member){return`<article class="join-card" data-member="${esc(member.id)}"><div class="join-top"><div class="avatar yellow">${esc(initials(member.full_name||member.email))}</div><div class="join-copy"><strong>${esc(member.full_name||'New team request')}</strong><span>${esc(member.email)}</span></div><span class="pending-pill">VERIFY IDENTITY</span></div><div class="join-meta"><div><small>Joined with</small><strong>Team Code</strong></div><div><small>Requested</small><strong>${esc(timeAgo(member.created_at))}</strong></div><div><small>Current access</small><strong>Locked</strong></div></div><div class="join-actions"><select aria-label="Role"><option value="estimator">Estimator</option><option value="manager">Project Manager</option><option value="site_supervisor">Site Supervisor</option></select><button class="btn primary" data-action="approve" type="button">Approve</button><button class="btn danger" data-action="decline" type="button">Remove</button></div></article>`}
  function renderOverview(){const requests=pending();$('requestList').innerHTML=requests.length?requests.slice(0,2).map(requestCard).join('<div style="height:8px"></div>'):'<div class="empty">No new Team Code requests. Your workspace is clear.</div>';$('presenceList').innerHTML=activeMembers().slice(0,5).map(member=>{const session=latestSession(member.id),isOnline=online(session);return`<div class="person"><div class="avatar">${esc(initials(member.full_name||member.email))}</div><div class="person-copy"><strong>${esc(member.full_name||member.email)}</strong><span>${esc(roleLabel(member.role))} • ${esc(member.email)}</span></div><div class="presence ${isOnline?'online':''}"><i></i>${isOnline?'Online':timeAgo(session?.last_seen_at)}</div></div>`}).join('');$('latestActivity').innerHTML=latestEvents().slice(0,7).map(eventHtml).join('')||'<div class="empty">No company activity has been recorded yet.</div>'}
  function eventHtml(event){const info=eventInfo(event);return`<article class="event"><div class="event-icon ${info.tone}">${esc(info.icon)}</div><div class="event-copy"><strong>${esc(info.title)}</strong><span>${esc(memberName(event.actor_id))} • ${esc(info.detail)}</span></div><time>${esc(timeAgo(event.created_at))}</time></article>`}
  function renderTeam(){
    const query=$('teamSearch').value.toLowerCase().trim(),roleFilter=$('teamRoleFilter').value,status=$('teamStatusFilter').value;
    const rows=state.members.filter(member=>{const text=`${member.full_name} ${member.email}`.toLowerCase(),status=member.role==='pending'?'pending':member.active===false?'inactive':'active';return(!query||text.includes(query))&&(!roleFilter||member.role===roleFilter)&&(!$('teamStatusFilter').value||status===$('teamStatusFilter').value)});
    $('staffRows').innerHTML=rows.map(member=>{const session=latestSession(member.id),isOnline=online(session),isOwner=member.role==='owner',isPending=member.role==='pending';return`<tr data-member="${esc(member.id)}"><td><div class="staff-name"><div class="avatar ${isOwner?'yellow':''}">${esc(initials(member.full_name||member.email))}</div><div><strong>${esc(member.full_name||'Team member')}</strong><span>${esc(member.email)}</span></div></div></td><td>${isPending?'<span class="status-pill off">Awaiting role</span>':isOwner?'<strong>Owner / Admin</strong>':`<select class="role-select" data-action="role"><option value="estimator" ${member.role==='estimator'?'selected':''}>Estimator</option><option value="manager" ${member.role==='manager'?'selected':''}>Project Manager</option><option value="site_supervisor" ${member.role==='site_supervisor'?'selected':''}>Site Supervisor</option></select>`}</td><td><span class="status-pill ${member.active===false?'off':''}">${isPending?'Pending':member.active===false?'Revoked':'Active'}</span></td><td>${esc(dateTime(session?.started_at))}</td><td><span class="presence ${isOnline?'online':''}"><i></i>${esc(isOnline?'Online now':timeAgo(session?.last_seen_at))}</span></td><td>${todayMinutes(member.id)} min</td><td><div class="row-actions">${isPending?'<button data-action="review">Review</button>':isOwner?'—':`<button data-action="message">Message</button><button data-action="access">${member.active===false?'Restore':'Revoke'}</button>`}</div></td></tr>`}).join('')||'<tr><td colspan="7" class="empty">No team members match this filter.</td></tr>';
  }
  function activityType(event){if(/^session_|signed_/.test(event.action))return'session';if(/checklist/.test(event.action))return'checklist';if(/member_|team_code/.test(event.action))return'team';if(/message|file_shared/.test(event.action))return'chat';return'project'}
  function filteredEvents(){const q=$('activitySearch').value.toLowerCase().trim(),type=$('activityType').value,days=Number($('activityRange').value||30),cutoff=Date.now()-days*86400000;return latestEvents().filter(event=>{const info=eventInfo(event),text=`${info.title} ${info.detail} ${memberName(event.actor_id)} ${event.module}`.toLowerCase();return new Date(event.created_at).getTime()>=cutoff&&(!state.selectedMember||event.actor_id===state.selectedMember)&&(!type||activityType(event)===type)&&(!q||text.includes(q))})}
  function renderActivity(){const counts=new Map(state.members.map(member=>[member.id,state.events.filter(event=>event.actor_id===member.id).length]));$('auditPeople').innerHTML=`<button class="audit-person ${!state.selectedMember?'active':''}" data-person=""><div class="avatar yellow">AC</div><div><span>All staff activity</span><small>Complete company timeline</small></div><b class="audit-count">${state.events.length}</b></button>`+state.members.filter(member=>member.active!==false||member.role==='owner').map(member=>`<button class="audit-person ${state.selectedMember===member.id?'active':''}" data-person="${esc(member.id)}"><div class="avatar">${esc(initials(member.full_name||member.email))}</div><div><span>${esc(member.full_name||member.email)}</span><small>${esc(roleLabel(member.role))}</small></div><b class="audit-count">${counts.get(member.id)||0}</b></button>`).join('');const events=filteredEvents();$('auditTitle').textContent=state.selectedMember?`${memberName(state.selectedMember)} activity`:'All staff activity';$('auditTotal').textContent=`${events.length} event${events.length===1?'':'s'}`;let day='';$('auditStream').innerHTML=events.map(event=>{const next=new Date(event.created_at).toLocaleDateString('en-AU',{weekday:'long',day:'numeric',month:'long'}),head=next!==day?(day=next,`<div class="audit-day">${esc(next)}</div>`):'';return head+eventHtml(event)}).join('')||'<div class="empty">No activity matches these filters.</div>'}
  function relevantMessages(){const me=currentUser()?.id;if(!state.selectedChat)return state.messages.filter(message=>message.recipient_id===null);return state.messages.filter(message=>(message.sender_id===me&&message.recipient_id===state.selectedChat)||(message.sender_id===state.selectedChat&&message.recipient_id===me))}
  function renderChat(){const me=currentUser()?.id,people=activeMembers().filter(member=>member.id!==me);$('conversationList').innerHTML=`<button class="conversation ${!state.selectedChat?'active':''}" data-chat=""><div class="avatar yellow">AC</div><div><strong>Entire team</strong><span>Company channel</span></div><time>${state.messages.filter(m=>m.recipient_id===null).length}</time></button>`+people.map(member=>`<button class="conversation ${state.selectedChat===member.id?'active':''}" data-chat="${esc(member.id)}"><div class="avatar">${esc(initials(member.full_name||member.email))}</div><div><strong>${esc(member.full_name||member.email)}</strong><span>${esc(roleLabel(member.role))}</span></div><time>${esc(timeAgo(latestSession(member.id)?.last_seen_at))}</time></button>`).join('');const selected=state.members.find(member=>member.id===state.selectedChat);$('chatAvatar').textContent=selected?initials(selected.full_name||selected.email):'AC';$('chatName').textContent=selected?(selected.full_name||selected.email):'Entire team';$('chatMeta').textContent=selected?`${roleLabel(selected.role)} • ${selected.email}`:'Company channel';$('messageText').placeholder=selected?`Message ${selected.full_name||selected.email}…`:'Message the entire team…';const rows=relevantMessages();$('messages').innerHTML=rows.length?rows.map(message=>`<article class="message ${message.sender_id===me?'mine':''}"><strong>${esc(memberName(message.sender_id))}</strong>${message.body?`<span>${esc(message.body)}</span>`:''}${message.attachment_path?`<button class="attachment" data-file="${esc(message.attachment_path)}" type="button">📎 ${esc(message.attachment_name||'Attachment')}</button>`:''}<time>${esc(dateTime(message.created_at))}</time></article>`).join(''):'<div class="empty">No messages yet. Start the conversation.</div>';$('messages').scrollTop=$('messages').scrollHeight}
  function renderAll(){$('ownerEmail').textContent=currentUser()?.email||'Owner account';renderStats();renderOverview();renderTeam();renderActivity();renderChat()}
  function switchView(view){document.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===view));document.querySelectorAll('[data-view-panel]').forEach(panel=>panel.classList.toggle('active',panel.dataset.viewPanel===view));if(view==='messages')renderChat();if(view==='activity')renderActivity();if(view==='team')renderTeam();scrollTo({top:0,behavior:'smooth'})}
  function notice(text){const bar=document.createElement('div');bar.className='preview-note';bar.style.display='block';bar.textContent=text;document.body.appendChild(bar);setTimeout(()=>bar.remove(),3200)}
  async function reviewMember(card,approve){const role=card.querySelector('select').value,memberId=card.dataset.member;if(preview){const member=state.members.find(item=>item.id===memberId);if(approve){member.role=role;member.active=true}else member.role='rejected';state.events.unshift({id:crypto.randomUUID(),actor_id:currentUser().id,action:approve?'member_join_approved':'member_join_rejected',module:'accounts',details:{member_id:memberId,assigned_role:role},created_at:new Date().toISOString()});renderAll();notice(approve?`Sample member approved as ${roleLabel(role)}.`:'Sample request removed.');return}await rpc('review_ac_join_request',{p_user:memberId,p_role:role,p_approve:approve});await ACAuth.loadProfile();await load()}
  async function changeRole(memberId,value){if(preview){state.members.find(item=>item.id===memberId).role=value;renderAll();notice(`Sample role changed to ${roleLabel(value)}.`);return}await rpc('set_ac_member_role',{p_user:memberId,p_role:value});await load()}
  async function changeAccess(memberId){const member=state.members.find(item=>item.id===memberId),next=member.active===false;if(!next&&!confirm(`Revoke ${member.full_name||member.email}? Their access will stop immediately and the Team Code will rotate.`))return;if(preview){member.active=next;renderAll();notice(`Sample access ${next?'restored':'revoked'}.`);return}await rpc('set_ac_member_access',{p_user:memberId,p_active:next});await load()}
  async function copyCode(){const code=state.organisation?.join_code;if(!code)return notice('Team Code is unavailable.');try{await navigator.clipboard.writeText(code);notice(`Team Code copied: ${code}`)}catch(_){notice(`Team Code: ${code}`)}}
  async function rotateCode(){if(!confirm('Rotate the Team Code? The old code will stop working immediately.'))return;if(preview){state.organisation.join_code='AC-'+Math.random().toString(36).slice(2,8).toUpperCase();renderAll();notice(`Sample Team Code rotated to ${state.organisation.join_code}.`);return}await rpc('rotate_ac_join_code');await load();notice('Team Code rotated successfully.')}
  async function uploadFile(file){if(!file)return null;if(file.size>MAX_FILE)throw new Error('Attachments must be 10 MB or smaller.');const profile=currentProfile(),user=currentUser(),clean=file.name.replace(/[^a-zA-Z0-9._-]/g,'_').slice(-100),path=`${profile.organisation_id}/${user.id}/${crypto.randomUUID()}-${clean}`;const response=await fetch(`${apiBase}/storage/v1/object/ac-team-chat/${path}`,{method:'POST',headers:{apikey:config.publishableKey||'',Authorization:(await ACAuth.headers()).Authorization,'Content-Type':file.type||'application/octet-stream','x-upsert':'false'},body:file}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||data.error||'The attachment could not be uploaded.');return{path,name:file.name.slice(0,180),type:(file.type||'application/octet-stream').slice(0,120),size:file.size}}
  async function sendMessage(text,file){const body=String(text||'').trim();if(!body&&!file)throw new Error('Write a message or attach a file.');if(preview){state.messages.push({id:crypto.randomUUID(),sender_id:currentUser().id,recipient_id:state.selectedChat||null,body,attachment_name:file?.name||null,attachment_path:file?'preview/new':null,created_at:new Date().toISOString()});renderAll();return}const attachment=await uploadFile(file),profile=currentProfile(),user=currentUser();await request('/rest/v1/ac_team_messages',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({organisation_id:profile.organisation_id,sender_id:user.id,recipient_id:state.selectedChat||null,body:body.slice(0,2000),attachment_path:attachment?.path||null,attachment_name:attachment?.name||null,attachment_type:attachment?.type||null,attachment_size:attachment?.size||null})});await load()}
  async function openAttachment(path){if(preview)return notice('Attachment links activate after the Supabase chat migration is installed.');const data=await request(`/storage/v1/object/sign/ac-team-chat/${path}`,{method:'POST',body:JSON.stringify({expiresIn:3600})}),url=data.signedURL?.startsWith('http')?data.signedURL:apiBase+String(data.signedURL||'');if(url)window.open(url,'_blank','noopener')}
  function exportCsv(){const rows=filteredEvents(),quote=value=>`"${String(value??'').replace(/"/g,'""')}"`,csv=['Time,Person,Role,Action,Module,Detail',...rows.map(event=>{const info=eventInfo(event),member=state.members.find(item=>item.id===event.actor_id);return[event.created_at,memberName(event.actor_id),roleLabel(member?.role),info.title,event.module,info.detail].map(quote).join(',')})].join('\n'),blob=new Blob([csv],{type:'text/csv'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`AC-activity-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(link.href)}

  document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.view)));document.querySelectorAll('[data-open-view]').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.openView)));
  $('refreshBtn').addEventListener('click',load);$('copyTeamCode').addEventListener('click',copyCode);$('inviteCopy').addEventListener('click',copyCode);$('rotateTeamCode').addEventListener('click',rotateCode);
  $('requestList').addEventListener('click',event=>{const button=event.target.closest('[data-action]');if(button)reviewMember(button.closest('[data-member]'),button.dataset.action==='approve').catch(error=>notice(error.message))});
  ['teamSearch','teamRoleFilter','teamStatusFilter'].forEach(id=>$(id).addEventListener('input',renderTeam));
  $('staffRows').addEventListener('change',event=>{if(event.target.matches('[data-action="role"]'))changeRole(event.target.closest('tr').dataset.member,event.target.value).catch(error=>notice(error.message))});
  $('staffRows').addEventListener('click',event=>{const button=event.target.closest('[data-action]');if(!button)return;const memberId=button.closest('tr').dataset.member;if(button.dataset.action==='access')changeAccess(memberId).catch(error=>notice(error.message));if(button.dataset.action==='message'){state.selectedChat=memberId;switchView('messages')}if(button.dataset.action==='review')switchView('overview')});
  ['activitySearch','activityType','activityRange'].forEach(id=>$(id).addEventListener('input',renderActivity));$('auditPeople').addEventListener('click',event=>{const button=event.target.closest('[data-person]');if(!button)return;state.selectedMember=button.dataset.person;renderActivity()});$('exportActivity').addEventListener('click',exportCsv);
  $('conversationList').addEventListener('click',event=>{const button=event.target.closest('[data-chat]');if(!button)return;state.selectedChat=button.dataset.chat;renderChat()});$('messages').addEventListener('click',event=>{const button=event.target.closest('[data-file]');if(button)openAttachment(button.dataset.file).catch(error=>notice(error.message))});
  $('messageFile').addEventListener('change',()=>{$('messageFileName').textContent=$('messageFile').files?.[0]?.name||''});$('messageForm').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;button.textContent='Sending…';try{await sendMessage($('messageText').value,$('messageFile').files?.[0]||null);$('messageText').value='';$('messageFile').value='';$('messageFileName').textContent=''}catch(error){notice(error.message)}finally{button.disabled=false;button.textContent='Send message'}});
  if(preview)document.body.classList.add('preview');load();
  if(!preview)setInterval(()=>{if(document.visibilityState==='visible')load().catch(()=>{})},60000);
})();
